"""项目级常量。"""

from pathlib import Path

DEFAULT_DB_PATH = Path("data/macro.duckdb")
DEFAULT_HTTP_TIMEOUT_SECONDS = 20
DEFAULT_USER_AGENT = "local-macro-monitor/0.1"

DATE_FORMAT = "%Y-%m-%d"
US_TREASURY_BACKFILL_START_YEAR = 2020
PBC_STATS_YEAR_START = 2020
PBC_STATS_YEAR_INDEX_PATHS = {
    2023: "4780803",
}

NEA_PUBLIC_SERIES = {
    "CN_SOCIETY_ELECTRICITY": {"metric": "total", "kind": "value"},
    "CN_SOCIETY_ELECTRICITY_YOY": {"metric": "total", "kind": "yoy"},
    "CN_PRIMARY_INDUSTRY_ELECTRICITY": {"metric": "primary", "kind": "value"},
    "CN_PRIMARY_INDUSTRY_ELECTRICITY_YOY": {"metric": "primary", "kind": "yoy"},
    "CN_SECONDARY_INDUSTRY_ELECTRICITY": {"metric": "secondary", "kind": "value"},
    "CN_SECONDARY_INDUSTRY_ELECTRICITY_YOY": {"metric": "secondary", "kind": "yoy"},
    "CN_TERTIARY_INDUSTRY_ELECTRICITY": {"metric": "tertiary", "kind": "value"},
    "CN_TERTIARY_INDUSTRY_ELECTRICITY_YOY": {"metric": "tertiary", "kind": "yoy"},
    "CN_RESIDENTIAL_ELECTRICITY": {"metric": "residential", "kind": "value"},
    "CN_RESIDENTIAL_ELECTRICITY_YOY": {"metric": "residential", "kind": "yoy"},
}

ASKCI_PUBLIC_SERIES = {
    "CN_THERMAL_POWER_GENERATION": {"indicator": "a03010h", "value_kind": "monthly_value"},
    "CN_HYDRO_POWER_GENERATION": {"indicator": "a03010i", "value_kind": "monthly_value"},
    "CN_NUCLEAR_POWER_GENERATION": {"indicator": "a03010j", "value_kind": "monthly_value"},
    "CN_WIND_POWER_GENERATION": {"indicator": "a03010k", "value_kind": "monthly_value"},
    "CN_SOLAR_POWER_GENERATION": {"indicator": "a03010l", "value_kind": "monthly_value"},
}

FRED_TREASURY_SERIES = {
    "US_DGS3MO": "DGS3MO",
    "US_DGS2": "DGS2",
    "US_DGS5": "DGS5",
    "US_DGS10": "DGS10",
    "US_DGS30": "DGS30",
}

US_TREASURY_SERIES = {
    "US_DGS3MO": "3 Mo",
    "US_DGS2": "2 Yr",
    "US_DGS5": "5 Yr",
    "US_DGS10": "10 Yr",
    "US_DGS30": "30 Yr",
}

FRED_SERIES = {
    "JP_LONG_RATE": "IRLTLT01JPM156N",
    "DE_LONG_RATE": "IRLTLT01DEM156N",
    "EU_LONG_RATE": "IRLTLT01EZM156N",
    "US_GDP": "GDP",
    "US_FEDERAL_DEBT": "GFDEBTN",
    "US_DEBT_TO_GDP": "GFDEGDQ188S",
    "US_FISCAL_BALANCE_TO_GDP": "FYFSGDA188S",
    "CU_PRICE": "PCOPPUSDM",
    "AL_PRICE": "PALUMUSDM",
    "NI_PRICE": "PNICKUSDM",
    "ZN_PRICE": "PZINCUSDM",
    "PB_PRICE": "PLEADUSDM",
    "IRON_ORE_PRICE": "PIORECRUSDM",
    "OIL_BRENT_PRICE": "DCOILBRENTEU",
    "OIL_WTI_PRICE": "DCOILWTICO",
    "US_GASOLINE_PRICE": "GASREGW",
    "EU_NATURAL_GAS_PRICE": "PNGASEUUSDM",
    "COAL_AUSTRALIA_PRICE": "PCOALAUUSDM",
    "US_POWER_PRODUCTION": "IPG2211A2N",
}

WORLD_BANK_SERIES = {
    "CN_GDP": ("CHN", "NY.GDP.MKTP.CD"),
    "CN_REAL_GDP_GROWTH": ("CHN", "NY.GDP.MKTP.KD.ZG"),
    "CN_HOUSEHOLD_CONSUMPTION": ("CHN", "NE.CON.PRVT.CD"),
    "CN_GROSS_CAPITAL_FORMATION": ("CHN", "NE.GDI.TOTL.CD"),
    "CN_INDUSTRY_VALUE_ADDED": ("CHN", "NV.IND.TOTL.CD"),
    "CN_EXPORTS_GOODS_SERVICES": ("CHN", "NE.EXP.GNFS.CD"),
    "CN_IMPORTS_GOODS_SERVICES": ("CHN", "NE.IMP.GNFS.CD"),
    "CN_CPI_INFLATION": ("CHN", "FP.CPI.TOTL.ZG"),
    "CN_OFFICIAL_EXCHANGE_RATE": ("CHN", "PA.NUS.FCRF"),
    "JP_GDP": ("JPN", "NY.GDP.MKTP.CD"),
    "EU_GDP": ("EMU", "NY.GDP.MKTP.CD"),
    "CN_DEBT_TO_GDP": ("CHN", "GC.DOD.TOTL.GD.ZS"),
    "JP_DEBT_TO_GDP": ("JPN", "GC.DOD.TOTL.GD.ZS"),
    "EU_DEBT_TO_GDP": ("EMU", "GC.DOD.TOTL.GD.ZS"),
    "CN_FISCAL_BALANCE_TO_GDP": ("CHN", "GC.NLD.TOTL.GD.ZS"),
    "JP_FISCAL_BALANCE_TO_GDP": ("JPN", "GC.NLD.TOTL.GD.ZS"),
    "EU_FISCAL_BALANCE_TO_GDP": ("EMU", "GC.NLD.TOTL.GD.ZS"),
}

CHINA_DATA_SERIES = {
    "CN_M2": "china-m2-money-supply",
}

PBC_PUBLIC_SERIES = {
    "CN_TOTAL_SOCIAL_FINANCING": {
        "table": "social_financing_flow",
        "row_label": "社会融资规模增量",
        "source": "PBOC:社会融资规模增量统计表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_SF_RMB_LOAN_FLOW": {
        "table": "social_financing_flow",
        "row_label": "人民币贷款",
        "source": "PBOC:社会融资规模增量统计表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_SF_FOREIGN_CURRENCY_LOAN_FLOW": {
        "table": "social_financing_flow",
        "row_label": "外币贷款（折合人民币）",
        "source": "PBOC:社会融资规模增量统计表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_SF_ENTRUSTED_LOAN_FLOW": {
        "table": "social_financing_flow",
        "row_label": "委托贷款",
        "source": "PBOC:社会融资规模增量统计表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_SF_TRUST_LOAN_FLOW": {
        "table": "social_financing_flow",
        "row_label": "信托贷款",
        "source": "PBOC:社会融资规模增量统计表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_SF_UNDISCOUNTED_BANK_ACCEPTANCE_FLOW": {
        "table": "social_financing_flow",
        "row_label": "未贴现银行承兑汇票",
        "source": "PBOC:社会融资规模增量统计表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_SF_CORPORATE_BOND_FLOW": {
        "table": "social_financing_flow",
        "row_label": "企业债券",
        "source": "PBOC:社会融资规模增量统计表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_SF_GOVERNMENT_BOND_FLOW": {
        "table": "social_financing_flow",
        "row_label": "政府债券",
        "source": "PBOC:社会融资规模增量统计表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_SF_EQUITY_FINANCING_FLOW": {
        "table": "social_financing_flow",
        "row_label": "非金融企业境内股票融资",
        "source": "PBOC:社会融资规模增量统计表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_SF_ABS_FLOW": {
        "table": "social_financing_flow",
        "row_label": "存款类金融机构资产支持证券",
        "source": "PBOC:社会融资规模增量统计表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_SF_LOAN_WRITEOFF_FLOW": {
        "table": "social_financing_flow",
        "row_label": "贷款核销",
        "source": "PBOC:社会融资规模增量统计表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_TOTAL_SOCIAL_FINANCING_STOCK": {
        "table": "social_financing_stock",
        "row_label": "社会融资规模存量",
        "source": "PBOC:社会融资规模存量统计表",
        "unit_multiplier": "10000",
        "value_transform": "level",
    },
    "CN_SF_RMB_LOAN_STOCK": {
        "table": "social_financing_stock",
        "row_label": "人民币贷款",
        "source": "PBOC:社会融资规模存量统计表",
        "unit_multiplier": "10000",
        "value_transform": "level",
    },
    "CN_SF_FOREIGN_CURRENCY_LOAN_STOCK": {
        "table": "social_financing_stock",
        "row_label": "外币贷款（折合人民币）",
        "source": "PBOC:社会融资规模存量统计表",
        "unit_multiplier": "10000",
        "value_transform": "level",
    },
    "CN_SF_ENTRUSTED_LOAN_STOCK": {
        "table": "social_financing_stock",
        "row_label": "委托贷款",
        "source": "PBOC:社会融资规模存量统计表",
        "unit_multiplier": "10000",
        "value_transform": "level",
    },
    "CN_SF_TRUST_LOAN_STOCK": {
        "table": "social_financing_stock",
        "row_label": "信托贷款",
        "source": "PBOC:社会融资规模存量统计表",
        "unit_multiplier": "10000",
        "value_transform": "level",
    },
    "CN_SF_UNDISCOUNTED_BANK_ACCEPTANCE_STOCK": {
        "table": "social_financing_stock",
        "row_label": "未贴现银行承兑汇票",
        "source": "PBOC:社会融资规模存量统计表",
        "unit_multiplier": "10000",
        "value_transform": "level",
    },
    "CN_SF_CORPORATE_BOND_STOCK": {
        "table": "social_financing_stock",
        "row_label": "企业债券",
        "source": "PBOC:社会融资规模存量统计表",
        "unit_multiplier": "10000",
        "value_transform": "level",
    },
    "CN_SF_GOVERNMENT_BOND_STOCK": {
        "table": "social_financing_stock",
        "row_label": "政府债券",
        "source": "PBOC:社会融资规模存量统计表",
        "unit_multiplier": "10000",
        "value_transform": "level",
    },
    "CN_SF_EQUITY_FINANCING_STOCK": {
        "table": "social_financing_stock",
        "row_label": "非金融企业境内股票",
        "source": "PBOC:社会融资规模存量统计表",
        "unit_multiplier": "10000",
        "value_transform": "level",
    },
    "CN_SF_ABS_STOCK": {
        "table": "social_financing_stock",
        "row_label": "存款类金融机构资产支持证券",
        "source": "PBOC:社会融资规模存量统计表",
        "unit_multiplier": "10000",
        "value_transform": "level",
    },
    "CN_SF_LOAN_WRITEOFF_STOCK": {
        "table": "social_financing_stock",
        "row_label": "贷款核销",
        "source": "PBOC:社会融资规模存量统计表",
        "unit_multiplier": "10000",
        "value_transform": "level",
    },
    "CN_RMB_LOANS": {
        "table": "rmb_credit",
        "row_label": "一、各项贷款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "monthly_change",
    },
    "CN_RMB_LOAN_BALANCE": {
        "table": "rmb_credit",
        "row_label": "一、各项贷款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_RMB_DEPOSIT_BALANCE": {
        "table": "rmb_credit",
        "row_label": "一、各项存款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_HOUSEHOLD_DEPOSIT_BALANCE": {
        "table": "rmb_credit",
        "row_label": "1.住户存款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_NONFINANCIAL_ENTERPRISE_DEPOSIT_BALANCE": {
        "table": "rmb_credit",
        "row_label": "2.非金融企业存款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_HOUSEHOLD_LOAN_INCREMENT": {
        "table": "rmb_credit",
        "row_label": "1.住户贷款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "monthly_change",
    },
    "CN_HOUSEHOLD_LOAN_BALANCE": {
        "table": "rmb_credit",
        "row_label": "1.住户贷款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_HOUSEHOLD_SHORT_TERM_LOAN_INCREMENT": {
        "table": "rmb_credit",
        "row_label": "（1）短期贷款",
        "row_context": "住户贷款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "monthly_change",
    },
    "CN_HOUSEHOLD_SHORT_TERM_LOAN_BALANCE": {
        "table": "rmb_credit",
        "row_label": "（1）短期贷款",
        "row_context": "住户贷款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_HOUSEHOLD_MEDIUM_LONG_TERM_LOAN_INCREMENT": {
        "table": "rmb_credit",
        "row_label": "（2） 中长期贷款",
        "row_context": "住户贷款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "monthly_change",
    },
    "CN_HOUSEHOLD_MEDIUM_LONG_TERM_LOAN_BALANCE": {
        "table": "rmb_credit",
        "row_label": "（2） 中长期贷款",
        "row_context": "住户贷款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
    "CN_ENTERPRISE_LOAN_INCREMENT": {
        "table": "rmb_credit",
        "row_label": "2.企（事）业单位贷款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "monthly_change",
    },
    "CN_ENTERPRISE_SHORT_TERM_LOAN_INCREMENT": {
        "table": "rmb_credit",
        "row_label": "（1）短期贷款",
        "row_context": "企（事）业单位贷款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "monthly_change",
    },
    "CN_ENTERPRISE_MEDIUM_LONG_TERM_LOAN_INCREMENT": {
        "table": "rmb_credit",
        "row_label": "（2）中长期贷款",
        "row_context": "企（事）业单位贷款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "monthly_change",
    },
    "CN_ENTERPRISE_BILL_FINANCING_INCREMENT": {
        "table": "rmb_credit",
        "row_label": "（3）票据融资",
        "row_context": "企（事）业单位贷款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "monthly_change",
    },
    "CN_ENTERPRISE_LOAN_BALANCE": {
        "table": "rmb_credit",
        "row_label": "2.企（事）业单位贷款",
        "source": "PBOC:金融机构人民币信贷收支表",
        "unit_multiplier": "1",
        "value_transform": "level",
    },
}

COAL_PUBLIC_SERIES = {
    "CCTD_HUANGLING_QI_COAL": {
        "type": "cctd_price",
        "url": "https://www.cctd.com.cn/Echarts/data/CCTD_PRICE_HL.php",
        "value_field": "age",
        "source": "CCTD:/Echarts/data/CCTD_PRICE_HL.php:age",
    },
    "CCTD_QHD_THERMAL_COAL_5500": {
        "type": "cctd_price",
        "url": "https://www.cctd.com.cn/Echarts/data/CCTD_PRICE_QHD.php",
        "value_field": "age",
        "source": "CCTD:/Echarts/data/CCTD_PRICE_QHD.php:age",
    },
    "CCTD_QHD_THERMAL_COAL_5000": {
        "type": "cctd_price",
        "url": "https://www.cctd.com.cn/Echarts/data/CCTD_PRICE_QHD.php",
        "value_field": "age1",
        "source": "CCTD:/Echarts/data/CCTD_PRICE_QHD.php:age1",
    },
    "CCTD_QHD_THERMAL_COAL_4500": {
        "type": "cctd_price",
        "url": "https://www.cctd.com.cn/Echarts/data/CCTD_PRICE_QHD.php",
        "value_field": "age2",
        "source": "CCTD:/Echarts/data/CCTD_PRICE_QHD.php:age2",
    },
    "CCTD_TANGSHAN_COKING_COAL": {
        "type": "cctd_price",
        "url": "https://www.cctd.com.cn/Echarts/data/CCTD_PRICE_TS.php",
        "value_field": "age",
        "source": "CCTD:/Echarts/data/CCTD_PRICE_TS.php:age",
    },
    "CCTD_TANGSHAN_FAT_COAL": {
        "type": "cctd_price",
        "url": "https://www.cctd.com.cn/Echarts/data/CCTD_PRICE_TS.php",
        "value_field": "age1",
        "source": "CCTD:/Echarts/data/CCTD_PRICE_TS.php:age1",
    },
    "CCTD_ORIGIN_SHANXI_THERMAL_COAL_5500": {
        "type": "cctd_price",
        "url": "https://www.cctd.com.cn/Echarts/data/CCTD_PRICE_CD.php",
        "value_field": "age",
        "source": "CCTD:/Echarts/data/CCTD_PRICE_CD.php:age",
    },
    "CFD_TTCI_THERMAL_COAL_5500": {
        "type": "cfd_latest",
        "url": "https://www.cfdcoal.com/api/indexs/home",
        "section": "ts_index",
        "date_field": "public_date",
        "value_field": "k5500",
        "source": "CFDCoal:/api/indexs/home:ts_index.k5500",
    },
    "CFD_TTCI_THERMAL_COAL_5000": {
        "type": "cfd_latest",
        "url": "https://www.cfdcoal.com/api/indexs/home",
        "section": "ts_index",
        "date_field": "public_date",
        "value_field": "k5000",
        "source": "CFDCoal:/api/indexs/home:ts_index.k5000",
    },
    "CFD_TTCI_THERMAL_COAL_4500": {
        "type": "cfd_latest",
        "url": "https://www.cfdcoal.com/api/indexs/home",
        "section": "ts_index",
        "date_field": "public_date",
        "value_field": "k4500",
        "source": "CFDCoal:/api/indexs/home:ts_index.k4500",
    },
    "CFD_TTCI_INDEX": {
        "type": "cfd_history",
        "url": "https://www.cfdcoal.com/api/indexs/home",
        "date_list_key": "ts_index_date",
        "value_list_key": "ts_index_9999",
        "source": "CFDCoal:/api/indexs/home:ts_index_9999",
    },
    "CFD_TOFI_INDEX": {
        "type": "cfd_history",
        "url": "https://www.cfdcoal.com/api/indexs/home",
        "date_list_key": "tofi_index_date",
        "value_list_key": "tofi_index",
        "source": "CFDCoal:/api/indexs/home:tofi_index",
    },
}

EIA_PUBLIC_SERIES = {
    "EIA_US_CRUDE_STOCKS_EX_SPR": {
        "series_id": "WCESTUS1",
        "source": "EIA dnav:WCESTUS1",
    },
    "EIA_US_TOTAL_CRUDE_STOCKS": {
        "series_id": "WCRSTUS1",
        "source": "EIA dnav:WCRSTUS1",
    },
    "EIA_CUSHING_CRUDE_STOCKS": {
        "series_id": "W_EPC0_SAX_YCUOK_MBBL",
        "source": "EIA dnav:W_EPC0_SAX_YCUOK_MBBL",
    },
    "EIA_US_SPR_CRUDE_STOCKS": {
        "series_id": "WCSSTUS1",
        "source": "EIA dnav:WCSSTUS1",
    },
    "EIA_US_CRUDE_PRODUCTION": {
        "series_id": "WCRFPUS2",
        "source": "EIA dnav:WCRFPUS2",
    },
    "EIA_LOWER48_CRUDE_PRODUCTION": {
        "series_id": "W_EPC0_FPF_R48_MBBLD",
        "source": "EIA dnav:W_EPC0_FPF_R48_MBBLD",
    },
    "EIA_US_CRUDE_IMPORTS": {
        "series_id": "WCRIMUS2",
        "source": "EIA dnav:WCRIMUS2",
    },
    "EIA_US_CRUDE_EXPORTS": {
        "series_id": "WCREXUS2",
        "source": "EIA dnav:WCREXUS2",
    },
    "EIA_US_REFINERY_CRUDE_INPUTS": {
        "series_id": "WCRRIUS2",
        "source": "EIA dnav:WCRRIUS2",
    },
    "EIA_US_REFINERY_UTILIZATION": {
        "series_id": "WPULEUS3",
        "source": "EIA dnav:WPULEUS3",
    },
    "EIA_US_TOTAL_GASOLINE_STOCKS": {
        "series_id": "WGTSTUS1",
        "source": "EIA dnav:WGTSTUS1",
    },
    "EIA_US_DISTILLATE_STOCKS": {
        "series_id": "WDISTUS1",
        "source": "EIA dnav:WDISTUS1",
    },
    "EIA_US_JET_FUEL_STOCKS": {
        "series_id": "WKJSTUS1",
        "source": "EIA dnav:WKJSTUS1",
    },
    "EIA_US_TOTAL_PETROLEUM_STOCKS": {
        "series_id": "WTTSTUS1",
        "source": "EIA dnav:WTTSTUS1",
    },
}

AKSHARE_CHINA_SERIES = {
    "CN_NOMINAL_GDP_QUARTERLY": {
        "function": "macro_china_gdp",
        "date_column": "季度",
        "value_column": "国内生产总值-绝对值",
        "source": "AKShare/Eastmoney:macro_china_gdp",
        "period_type": "quarter",
    },
    "CN_REAL_GDP_QUARTERLY_YOY": {
        "function": "macro_china_gdp",
        "date_column": "季度",
        "value_column": "国内生产总值-同比增长",
        "source": "AKShare/Eastmoney:macro_china_gdp",
        "period_type": "quarter",
    },
    "CN_NOMINAL_GDP_CURRENT_QUARTER_QOQ": {
        "function": "macro_china_gdp",
        "date_column": "季度",
        "source": "AKShare/Eastmoney:macro_china_gdp",
        "period_type": "quarter",
        "computed": "nominal_gdp_current_quarter_qoq",
    },
    "CN_RETAIL_SALES": {
        "function": "macro_china_consumer_goods_retail",
        "date_column": "月份",
        "value_column": "同比增长",
        "source": "AKShare/Eastmoney:macro_china_consumer_goods_retail",
        "period_type": "month",
    },
    "CN_INDUSTRIAL_PRODUCTION_YOY": {
        "function": "macro_china_gyzjz",
        "date_column": "月份",
        "value_column": "同比增长",
        "source": "AKShare/Eastmoney:macro_china_gyzjz",
        "period_type": "month",
    },
    "CN_FIXED_ASSET_INVESTMENT": {
        "function": "macro_china_gdzctz",
        "date_column": "月份",
        "value_column": "同比增长",
        "source": "AKShare/Eastmoney:macro_china_gdzctz",
        "period_type": "month",
    },
    "CN_M2": {
        "function": "macro_china_money_supply",
        "date_column": "月份",
        "value_column": "货币和准货币(M2)-数量(亿元)",
        "source": "AKShare/Eastmoney:macro_china_money_supply",
        "period_type": "month",
    },
    "CN_M2_YOY": {
        "function": "macro_china_money_supply",
        "date_column": "月份",
        "value_column": "货币和准货币(M2)-同比增长",
        "source": "AKShare/Eastmoney:macro_china_money_supply",
        "period_type": "month",
    },
    "CN_M1": {
        "function": "macro_china_money_supply",
        "date_column": "月份",
        "value_column": "货币(M1)-数量(亿元)",
        "source": "AKShare/Eastmoney:macro_china_money_supply",
        "period_type": "month",
    },
    "CN_M1_YOY": {
        "function": "macro_china_money_supply",
        "date_column": "月份",
        "value_column": "货币(M1)-同比增长",
        "source": "AKShare/Eastmoney:macro_china_money_supply",
        "period_type": "month",
    },
    "CN_M0": {
        "function": "macro_china_money_supply",
        "date_column": "月份",
        "value_column": "流通中的现金(M0)-数量(亿元)",
        "source": "AKShare/Eastmoney:macro_china_money_supply",
        "period_type": "month",
    },
    "CN_M0_YOY": {
        "function": "macro_china_money_supply",
        "date_column": "月份",
        "value_column": "流通中的现金(M0)-同比增长",
        "source": "AKShare/Eastmoney:macro_china_money_supply",
        "period_type": "month",
    },
    "CN_M1_M2_SCISSORS": {
        "function": "macro_china_money_supply",
        "date_column": "月份",
        "source": "AKShare/Eastmoney:macro_china_money_supply",
        "period_type": "month",
        "computed": "m1_yoy_minus_m2_yoy",
    },
    "CN_NEW_HOME_PRICE_INDEX": {
        "function": "macro_china_new_house_price",
        "date_column": "日期",
        "value_column": "新建商品住宅价格指数-同比",
        "source": "AKShare/Eastmoney:macro_china_new_house_price",
        "period_type": "date",
        "aggregate": "mean_by_date",
    },
    "CN_PPI": {
        "function": "macro_china_ppi",
        "date_column": "月份",
        "value_column": "当月同比增长",
        "source": "AKShare/Eastmoney:macro_china_ppi",
        "period_type": "month",
    },
    "CN_PPI_INDEX": {
        "function": "macro_china_ppi",
        "date_column": "月份",
        "value_column": "当月",
        "source": "AKShare/Eastmoney:macro_china_ppi",
        "period_type": "month",
    },
    "CN_PPI_MOM": {
        "function": "macro_china_ppi",
        "date_column": "月份",
        "value_column": "当月",
        "source": "AKShare/Eastmoney:macro_china_ppi",
        "period_type": "month",
        "computed": "index_mom_change",
    },
    "CN_CPI_MONTHLY_INDEX": {
        "function": "macro_china_cpi",
        "date_column": "月份",
        "value_column": "全国-当月",
        "source": "AKShare/Eastmoney:macro_china_cpi",
        "period_type": "month",
    },
    "CN_CPI_MONTHLY_YOY": {
        "function": "macro_china_cpi",
        "date_column": "月份",
        "value_column": "全国-同比增长",
        "source": "AKShare/Eastmoney:macro_china_cpi",
        "period_type": "month",
    },
    "CN_CPI_MONTHLY_MOM": {
        "function": "macro_china_cpi",
        "date_column": "月份",
        "value_column": "全国-环比增长",
        "source": "AKShare/Eastmoney:macro_china_cpi",
        "period_type": "month",
    },
    "CN_EXPORT_VALUE_USD": {
        "function": "macro_china_hgjck",
        "date_column": "月份",
        "value_column": "当月出口额-金额",
        "source": "AKShare/Customs:macro_china_hgjck",
        "period_type": "month",
        "multiplier": "0.00001",
    },
    "CN_IMPORT_VALUE_USD": {
        "function": "macro_china_hgjck",
        "date_column": "月份",
        "value_column": "当月进口额-金额",
        "source": "AKShare/Customs:macro_china_hgjck",
        "period_type": "month",
        "multiplier": "0.00001",
    },
    "CN_EXPORT_YOY_USD": {
        "function": "macro_china_hgjck",
        "date_column": "月份",
        "value_column": "当月出口额-同比增长",
        "source": "AKShare/Customs:macro_china_hgjck",
        "period_type": "month",
    },
    "CN_IMPORT_YOY_USD": {
        "function": "macro_china_hgjck",
        "date_column": "月份",
        "value_column": "当月进口额-同比增长",
        "source": "AKShare/Customs:macro_china_hgjck",
        "period_type": "month",
    },
    "CN_EXPORT_MOM_USD": {
        "function": "macro_china_hgjck",
        "date_column": "月份",
        "value_column": "当月出口额-金额",
        "source": "AKShare/Customs:macro_china_hgjck:export_mom",
        "period_type": "month",
        "multiplier": "0.00001",
        "computed": "customs_mom_change",
    },
    "CN_IMPORT_MOM_USD": {
        "function": "macro_china_hgjck",
        "date_column": "月份",
        "value_column": "当月进口额-金额",
        "source": "AKShare/Customs:macro_china_hgjck:import_mom",
        "period_type": "month",
        "multiplier": "0.00001",
        "computed": "customs_mom_change",
    },
    "CN_TRADE_BALANCE_USD": {
        "function": "macro_china_hgjck",
        "date_column": "月份",
        "export_column": "当月出口额-金额",
        "import_column": "当月进口额-金额",
        "source": "AKShare/Customs:macro_china_hgjck:trade_balance",
        "period_type": "month",
        "multiplier": "0.00001",
        "computed": "customs_trade_balance",
    },
    "CN_TRADE_BALANCE_MOM_USD": {
        "function": "macro_china_hgjck",
        "date_column": "月份",
        "export_column": "当月出口额-金额",
        "import_column": "当月进口额-金额",
        "source": "AKShare/Customs:macro_china_hgjck:trade_balance_mom",
        "period_type": "month",
        "multiplier": "0.00001",
        "computed": "customs_trade_balance_mom",
    },
    "CN_TRADE_BALANCE_YOY_USD": {
        "function": "macro_china_hgjck",
        "date_column": "月份",
        "export_column": "当月出口额-金额",
        "import_column": "当月进口额-金额",
        "source": "AKShare/Customs:macro_china_hgjck:trade_balance_yoy",
        "period_type": "month",
        "multiplier": "0.00001",
        "computed": "customs_trade_balance_yoy",
    },
    "CN_SHCOMP": {
        "function": "stock_zh_index_daily",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:stock_zh_index_daily:sh000001",
        "period_type": "date",
        "symbol": "sh000001",
    },
    "LME_COPPER_INVENTORY": {
        "function": "macro_euro_lme_stock",
        "date_column": "日期",
        "value_column": "铜-库存",
        "source": "AKShare/Jin10:macro_euro_lme_stock",
        "period_type": "date",
    },
    "LME_ALUMINUM_INVENTORY": {
        "function": "macro_euro_lme_stock",
        "date_column": "日期",
        "value_column": "铝-库存",
        "source": "AKShare/Jin10:macro_euro_lme_stock",
        "period_type": "date",
    },
    "LME_ZINC_INVENTORY": {
        "function": "macro_euro_lme_stock",
        "date_column": "日期",
        "value_column": "锌-库存",
        "source": "AKShare/Jin10:macro_euro_lme_stock",
        "period_type": "date",
    },
    "LME_NICKEL_INVENTORY": {
        "function": "macro_euro_lme_stock",
        "date_column": "日期",
        "value_column": "镍-库存",
        "source": "AKShare/Jin10:macro_euro_lme_stock",
        "period_type": "date",
    },
    "SHFE_COPPER_INVENTORY": {
        "function": "futures_inventory_em",
        "date_column": "日期",
        "value_column": "库存",
        "source": "AKShare/Eastmoney:futures_inventory_em:cu",
        "period_type": "date",
        "symbol": "cu",
    },
    "COMEX_GOLD_INVENTORY": {
        "function": "futures_comex_inventory",
        "date_column": "日期",
        "value_column": "COMEX黄金库存量-吨",
        "source": "AKShare/Eastmoney:futures_comex_inventory:黄金",
        "period_type": "date",
        "symbol": "黄金",
    },
    "CN_PBOC_GOLD_RESERVE": {
        "function": "macro_china_foreign_exchange_gold",
        "date_column": "统计时间",
        "value_column": "黄金储备",
        "source": "AKShare/Eastmoney:macro_china_foreign_exchange_gold:gold",
        "period_type": "decimal_month",
    },
    "CN_PBOC_FX_RESERVE": {
        "function": "macro_china_foreign_exchange_gold",
        "date_column": "统计时间",
        "value_column": "国家外汇储备",
        "source": "AKShare/Eastmoney:macro_china_foreign_exchange_gold:fx",
        "period_type": "decimal_month",
    },
    "CN_GOLD_ETF_HOLDINGS": {
        "function": "macro_cons_gold",
        "date_column": "日期",
        "value_column": "总库存",
        "source": "AKShare/Jin10:macro_cons_gold:holdings",
        "period_type": "date",
    },
    "CN_GOLD_ETF_HOLDINGS_CHANGE": {
        "function": "macro_cons_gold",
        "date_column": "日期",
        "value_column": "增持/减持",
        "source": "AKShare/Jin10:macro_cons_gold:change",
        "period_type": "date",
    },
    "SGE_AU9999_CLOSE": {
        "function": "spot_hist_sge",
        "symbol": "Au99.99",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/SGE:spot_hist_sge:Au99.99:close",
        "period_type": "date",
    },
    "SGE_GOLD_BENCHMARK_PM": {
        "function": "spot_golden_benchmark_sge",
        "date_column": "交易时间",
        "value_column": "晚盘价",
        "source": "AKShare/SGE:spot_golden_benchmark_sge:PM",
        "period_type": "date",
    },
    "SHFE_GOLD_FUTURES_CLOSE": {
        "function": "futures_zh_daily_sina",
        "symbol": "AU0",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:futures_zh_daily_sina:AU0:close",
        "period_type": "date",
    },
    "SHFE_GOLD_FUTURES_SETTLE": {
        "function": "futures_zh_daily_sina",
        "symbol": "AU0",
        "date_column": "date",
        "value_column": "settle",
        "source": "AKShare/Sina:futures_zh_daily_sina:AU0:settle",
        "period_type": "date",
    },
    "SHFE_SILVER_FUTURES_CLOSE": {
        "function": "futures_zh_daily_sina",
        "symbol": "AG0",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:futures_zh_daily_sina:AG0:close",
        "period_type": "date",
    },
    "SHFE_SILVER_FUTURES_SETTLE": {
        "function": "futures_zh_daily_sina",
        "symbol": "AG0",
        "date_column": "date",
        "value_column": "settle",
        "source": "AKShare/Sina:futures_zh_daily_sina:AG0:settle",
        "period_type": "date",
    },
    "CN_SILVER_ETF_HOLDINGS": {
        "function": "macro_cons_silver",
        "date_column": "日期",
        "value_column": "总库存",
        "source": "AKShare/Jin10:macro_cons_silver:holdings",
        "period_type": "date",
    },
    "CN_SILVER_ETF_HOLDINGS_CHANGE": {
        "function": "macro_cons_silver",
        "date_column": "日期",
        "value_column": "增持/减持",
        "source": "AKShare/Jin10:macro_cons_silver:change",
        "period_type": "date",
    },
    "SGE_AG9999_CLOSE": {
        "function": "spot_hist_sge",
        "symbol": "Ag99.99",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/SGE:spot_hist_sge:Ag99.99:close",
        "period_type": "date",
    },
    "SGE_SILVER_BENCHMARK_PM": {
        "function": "spot_silver_benchmark_sge",
        "date_column": "交易时间",
        "value_column": "晚盘价",
        "source": "AKShare/SGE:spot_silver_benchmark_sge:PM",
        "period_type": "date",
    },
    "SHFE_COPPER_FUTURES_CLOSE": {
        "function": "futures_zh_daily_sina",
        "symbol": "CU0",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:futures_zh_daily_sina:CU0:close",
        "period_type": "date",
    },
    "SHFE_COPPER_FUTURES_SETTLE": {
        "function": "futures_zh_daily_sina",
        "symbol": "CU0",
        "date_column": "date",
        "value_column": "settle",
        "source": "AKShare/Sina:futures_zh_daily_sina:CU0:settle",
        "period_type": "date",
    },
    "SHFE_ALUMINUM_FUTURES_CLOSE": {
        "function": "futures_zh_daily_sina",
        "symbol": "AL0",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:futures_zh_daily_sina:AL0:close",
        "period_type": "date",
    },
    "SHFE_ZINC_FUTURES_CLOSE": {
        "function": "futures_zh_daily_sina",
        "symbol": "ZN0",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:futures_zh_daily_sina:ZN0:close",
        "period_type": "date",
    },
    "SHFE_LEAD_FUTURES_CLOSE": {
        "function": "futures_zh_daily_sina",
        "symbol": "PB0",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:futures_zh_daily_sina:PB0:close",
        "period_type": "date",
    },
    "SHFE_NICKEL_FUTURES_CLOSE": {
        "function": "futures_zh_daily_sina",
        "symbol": "NI0",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:futures_zh_daily_sina:NI0:close",
        "period_type": "date",
    },
    "SHFE_TIN_FUTURES_CLOSE": {
        "function": "futures_zh_daily_sina",
        "symbol": "SN0",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:futures_zh_daily_sina:SN0:close",
        "period_type": "date",
    },
    "SHFE_ALUMINA_FUTURES_CLOSE": {
        "function": "futures_zh_daily_sina",
        "symbol": "AO0",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:futures_zh_daily_sina:AO0:close",
        "period_type": "date",
    },
    "GFEX_INDUSTRIAL_SILICON_FUTURES_CLOSE": {
        "function": "futures_zh_daily_sina",
        "symbol": "SI0",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:futures_zh_daily_sina:SI0:close",
        "period_type": "date",
    },
    "INE_BONDED_COPPER_FUTURES_CLOSE": {
        "function": "futures_zh_daily_sina",
        "symbol": "BC0",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:futures_zh_daily_sina:BC0:close",
        "period_type": "date",
    },
    "SHFE_COPPER_INVENTORY_DAILY": {
        "function": "futures_inventory_em",
        "symbol": "沪铜",
        "date_column": "日期",
        "value_column": "库存",
        "source": "AKShare/Eastmoney:futures_inventory_em:沪铜",
        "period_type": "date",
    },
    "SHFE_COPPER_99QH_INVENTORY": {
        "function": "futures_inventory_99",
        "symbol": "铜",
        "date_column": "日期",
        "value_column": "库存",
        "source": "AKShare/99qh:futures_inventory_99:铜:库存",
        "period_type": "date",
    },
    "SHFE_ALUMINUM_99QH_INVENTORY": {
        "function": "futures_inventory_99",
        "symbol": "铝",
        "date_column": "日期",
        "value_column": "库存",
        "source": "AKShare/99qh:futures_inventory_99:铝:库存",
        "period_type": "date",
    },
    "SHFE_ZINC_99QH_INVENTORY": {
        "function": "futures_inventory_99",
        "symbol": "锌",
        "date_column": "日期",
        "value_column": "库存",
        "source": "AKShare/99qh:futures_inventory_99:锌:库存",
        "period_type": "date",
    },
    "SHFE_NICKEL_99QH_INVENTORY": {
        "function": "futures_inventory_99",
        "symbol": "镍",
        "date_column": "日期",
        "value_column": "库存",
        "source": "AKShare/99qh:futures_inventory_99:镍:库存",
        "period_type": "date",
    },
    "SHFE_LEAD_99QH_INVENTORY": {
        "function": "futures_inventory_99",
        "symbol": "铅",
        "date_column": "日期",
        "value_column": "库存",
        "source": "AKShare/99qh:futures_inventory_99:铅:库存",
        "period_type": "date",
    },
    "CN_COMMODITY_PRICE_INDEX": {
        "function": "macro_china_commodity_price_index",
        "date_column": "日期",
        "value_column": "最新值",
        "source": "AKShare/Eastmoney:macro_china_commodity_price_index",
        "period_type": "date",
    },
    "US_CRUDE_OIL_PRODUCTION": {
        "function": "macro_usa_crude_inner",
        "date_column": "日期",
        "value_column": "美国国内原油总量-产量",
        "source": "AKShare/Jin10:macro_usa_crude_inner",
        "period_type": "date",
    },
    "US_CRUDE_OIL_PRODUCTION_CHANGE": {
        "function": "macro_usa_crude_inner",
        "date_column": "日期",
        "value_column": "美国国内原油总量-变化",
        "source": "AKShare/Jin10:macro_usa_crude_inner",
        "period_type": "date",
    },
    "CN_GASOLINE_RETAIL_PRICE": {
        "function": "energy_oil_hist",
        "date_column": "调整日期",
        "value_column": "汽油价格",
        "source": "AKShare/Eastmoney:energy_oil_hist",
        "period_type": "date",
    },
    "CN_DIESEL_RETAIL_PRICE": {
        "function": "energy_oil_hist",
        "date_column": "调整日期",
        "value_column": "柴油价格",
        "source": "AKShare/Eastmoney:energy_oil_hist",
        "period_type": "date",
    },
    "BDTI_INDEX": {
        "function": "macro_china_bdti_index",
        "date_column": "日期",
        "value_column": "最新值",
        "source": "AKShare/Eastmoney:macro_china_bdti_index",
        "period_type": "date",
    },
    "BCTI_INDEX": {
        "function": "macro_shipping_bcti",
        "date_column": "日期",
        "value_column": "最新值",
        "source": "AKShare/Eastmoney:macro_shipping_bcti",
        "period_type": "date",
    },
    "BDI_INDEX": {
        "function": "macro_shipping_bdi",
        "date_column": "日期",
        "value_column": "最新值",
        "source": "AKShare/Eastmoney:macro_shipping_bdi",
        "period_type": "date",
    },
    "BCI_INDEX": {
        "function": "macro_shipping_bci",
        "date_column": "日期",
        "value_column": "最新值",
        "source": "AKShare/Eastmoney:macro_shipping_bci",
        "period_type": "date",
    },
    "BPI_INDEX": {
        "function": "macro_shipping_bpi",
        "date_column": "日期",
        "value_column": "最新值",
        "source": "AKShare/Eastmoney:macro_shipping_bpi",
        "period_type": "date",
    },
    "CN_COKING_COAL_FUTURES_CLOSE": {
        "function": "futures_zh_daily_sina",
        "symbol": "JM0",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:futures_zh_daily_sina:JM0:close",
        "period_type": "date",
    },
    "CN_COKING_COAL_FUTURES_SETTLE": {
        "function": "futures_zh_daily_sina",
        "symbol": "JM0",
        "date_column": "date",
        "value_column": "settle",
        "source": "AKShare/Sina:futures_zh_daily_sina:JM0:settle",
        "period_type": "date",
    },
    "CN_COKE_FUTURES_CLOSE": {
        "function": "futures_zh_daily_sina",
        "symbol": "J0",
        "date_column": "date",
        "value_column": "close",
        "source": "AKShare/Sina:futures_zh_daily_sina:J0:close",
        "period_type": "date",
    },
    "CN_COKE_FUTURES_SETTLE": {
        "function": "futures_zh_daily_sina",
        "symbol": "J0",
        "date_column": "date",
        "value_column": "settle",
        "source": "AKShare/Sina:futures_zh_daily_sina:J0:settle",
        "period_type": "date",
    },
    "CN_COKING_COAL_99QH_INVENTORY": {
        "function": "futures_inventory_99",
        "symbol": "焦煤",
        "date_column": "日期",
        "value_column": "库存",
        "source": "AKShare/99qh:futures_inventory_99:焦煤:库存",
        "period_type": "date",
    },
    "CN_COKE_99QH_INVENTORY": {
        "function": "futures_inventory_99",
        "symbol": "焦炭",
        "date_column": "日期",
        "value_column": "库存",
        "source": "AKShare/99qh:futures_inventory_99:焦炭:库存",
        "period_type": "date",
    },
    "CN_METHANOL_99QH_INVENTORY": {
        "function": "futures_inventory_99",
        "symbol": "甲醇",
        "date_column": "日期",
        "value_column": "库存",
        "source": "AKShare/99qh:futures_inventory_99:甲醇:库存",
        "period_type": "date",
    },
    "CN_SOCIETY_ELECTRICITY": {
        "function": "macro_china_society_electricity",
        "date_column": "统计时间",
        "value_column": "全社会用电量",
        "source": "AKShare/Sina:macro_china_society_electricity",
        "period_type": "decimal_month",
        "multiplier": "0.0001",
    },
    "CN_SOCIETY_ELECTRICITY_YOY": {
        "function": "macro_china_society_electricity",
        "date_column": "统计时间",
        "value_column": "全社会用电量同比",
        "source": "AKShare/Sina:macro_china_society_electricity",
        "period_type": "decimal_month",
    },
    "CN_PRIMARY_INDUSTRY_ELECTRICITY": {
        "function": "macro_china_society_electricity",
        "date_column": "统计时间",
        "value_column": "第一产业用电量",
        "source": "AKShare/Sina:macro_china_society_electricity:primary",
        "period_type": "decimal_month",
        "multiplier": "0.0001",
    },
    "CN_PRIMARY_INDUSTRY_ELECTRICITY_YOY": {
        "function": "macro_china_society_electricity",
        "date_column": "统计时间",
        "value_column": "第一产业用电量同比",
        "source": "AKShare/Sina:macro_china_society_electricity:primary_yoy",
        "period_type": "decimal_month",
    },
    "CN_SECONDARY_INDUSTRY_ELECTRICITY": {
        "function": "macro_china_society_electricity",
        "date_column": "统计时间",
        "value_column": "第二产业用电量",
        "source": "AKShare/Sina:macro_china_society_electricity:secondary",
        "period_type": "decimal_month",
        "multiplier": "0.0001",
    },
    "CN_SECONDARY_INDUSTRY_ELECTRICITY_YOY": {
        "function": "macro_china_society_electricity",
        "date_column": "统计时间",
        "value_column": "第二产业用电量同比",
        "source": "AKShare/Sina:macro_china_society_electricity:secondary_yoy",
        "period_type": "decimal_month",
    },
    "CN_TERTIARY_INDUSTRY_ELECTRICITY": {
        "function": "macro_china_society_electricity",
        "date_column": "统计时间",
        "value_column": "第三产业用电量",
        "source": "AKShare/Sina:macro_china_society_electricity:tertiary",
        "period_type": "decimal_month",
        "multiplier": "0.0001",
    },
    "CN_TERTIARY_INDUSTRY_ELECTRICITY_YOY": {
        "function": "macro_china_society_electricity",
        "date_column": "统计时间",
        "value_column": "第三产业用电量同比",
        "source": "AKShare/Sina:macro_china_society_electricity:tertiary_yoy",
        "period_type": "decimal_month",
    },
    "CN_RESIDENTIAL_ELECTRICITY": {
        "function": "macro_china_society_electricity",
        "date_column": "统计时间",
        "value_column": "城乡居民生活用电量合计",
        "source": "AKShare/Sina:macro_china_society_electricity:residential",
        "period_type": "decimal_month",
        "multiplier": "0.0001",
    },
    "CN_RESIDENTIAL_ELECTRICITY_YOY": {
        "function": "macro_china_society_electricity",
        "date_column": "统计时间",
        "value_column": "城乡居民生活用电量合计同比",
        "source": "AKShare/Sina:macro_china_society_electricity:residential_yoy",
        "period_type": "decimal_month",
    },
    "CN_ENERGY_INDEX": {
        "function": "macro_china_energy_index",
        "date_column": "日期",
        "value_column": "最新值",
        "source": "AKShare/Eastmoney:macro_china_energy_index",
        "period_type": "date",
    },
    "CN_BEIJING_CARBON_AVG_PRICE": {
        "function": "energy_carbon_bj",
        "date_column": "日期",
        "value_column": "成交均价",
        "source": "AKShare/Beijing:energy_carbon_bj",
        "period_type": "date",
    },
    "CN_HUBEI_CARBON_PRICE": {
        "function": "energy_carbon_hb",
        "date_column": "日期",
        "value_column": "成交价",
        "source": "AKShare/Hubei:energy_carbon_hb",
        "period_type": "date",
    },
    "CN_MANUFACTURING_PMI": {
        "function": "macro_china_pmi",
        "date_column": "月份",
        "value_column": "制造业-指数",
        "source": "AKShare/Eastmoney:macro_china_pmi",
        "period_type": "month",
    },
    "CN_NON_MANUFACTURING_PMI": {
        "function": "macro_china_pmi",
        "date_column": "月份",
        "value_column": "非制造业-指数",
        "source": "AKShare/Eastmoney:macro_china_pmi",
        "period_type": "month",
    },
    "CN_CORPORATE_GOODS_PRICE_INDEX": {
        "function": "macro_china_qyspjg",
        "date_column": "月份",
        "value_column": "总指数-指数值",
        "source": "AKShare/Eastmoney:macro_china_qyspjg",
        "period_type": "month",
    },
    "US_ISM_MANUFACTURING_PMI": {
        "function": "macro_usa_ism_pmi",
        "date_column": "日期",
        "value_column": "今值",
        "source": "AKShare/Jin10:macro_usa_ism_pmi",
        "period_type": "date",
    },
    "US_UNEMPLOYMENT_RATE": {
        "function": "macro_usa_unemployment_rate",
        "date_column": "日期",
        "value_column": "今值",
        "source": "AKShare/Jin10:macro_usa_unemployment_rate",
        "period_type": "date",
    },
    "US_NONFARM_PAYROLLS": {
        "function": "macro_usa_non_farm",
        "date_column": "日期",
        "value_column": "今值",
        "source": "AKShare/Jin10:macro_usa_non_farm",
        "period_type": "date",
    },
    "US_CPI_YOY": {
        "function": "macro_usa_cpi_yoy",
        "date_column": "时间",
        "value_column": "现值",
        "source": "AKShare/Eastmoney:macro_usa_cpi_yoy",
        "period_type": "date",
    },
    "US_CORE_PCE_YOY": {
        "function": "macro_usa_core_pce_price",
        "date_column": "日期",
        "value_column": "今值",
        "source": "AKShare/Jin10:macro_usa_core_pce_price",
        "period_type": "date",
    },
    "US_RETAIL_SALES_MOM": {
        "function": "macro_usa_retail_sales",
        "date_column": "日期",
        "value_column": "今值",
        "source": "AKShare/Jin10:macro_usa_retail_sales",
        "period_type": "date",
    },
}

UNAVAILABLE_SERIES = {
    "CN_REAL_GDP": {
        "status": "pending_source",
        "reason": "公开可稳定抓取的是季度不变价同比发布值，尚未找到月度实际 GDP 水平官方接口。",
        "next_step": "如需月度实际 GDP 水平，接入 Wind 或确认国家统计局可访问的专用接口。",
    },
    "CN_MANUFACTURING_INVESTMENT": {
        "status": "pending_source",
        "reason": "尚未找到稳定返回制造业投资累计同比的公开接口。",
        "next_step": "接入国家统计局分项接口或 Wind。",
    },
    "CN_INFRASTRUCTURE_INVESTMENT": {
        "status": "pending_source",
        "reason": "尚未找到稳定返回基础设施投资累计同比的公开接口。",
        "next_step": "接入国家统计局分项接口或 Wind。",
    },
    "CN_REAL_ESTATE_INVESTMENT": {
        "status": "pending_source",
        "reason": "尚未找到稳定返回房地产开发投资累计同比的公开接口。",
        "next_step": "接入国家统计局房地产月度表或 Wind。",
    },
    "CN_PROPERTY_SALES_AREA": {
        "status": "pending_source",
        "reason": "尚未找到稳定返回商品房销售面积累计同比的公开接口。",
        "next_step": "接入国家统计局房地产月度表或 Wind。",
    },
    "CN_EXPORT_PRICE_INDEX": {
        "status": "pending_source",
        "reason": "尚未找到稳定返回海关出口价格指数的公开接口。",
        "next_step": "接入海关总署价格指数表或 Wind。",
    },
    "CN_IMPORT_PRICE_INDEX": {
        "status": "pending_source",
        "reason": "尚未找到稳定返回海关进口价格指数的公开接口。",
        "next_step": "接入海关总署价格指数表或 Wind。",
    },
    "US_EIA_CRUDE_STOCKS": {
        "status": "needs_key",
        "reason": "EIA 官方 API 需要 api_key，当前项目尚未配置可用密钥。",
        "next_step": "在 .env 中配置 EIA_API_KEY 后接入 EIA petroleum stocks 接口。",
    },
    "LME_COPPER_INVENTORY": {
        "status": "pending_source",
        "reason": "LME 库存数据需要稳定公开接口、授权数据源或 Wind。",
        "next_step": "确认 LME 授权接口、Wind 字段或可稳定下载的数据表。",
    },
    "SHFE_COPPER_INVENTORY": {
        "status": "pending_source",
        "reason": "上期所铜库存需要稳定解析交易所仓单或周库存表。",
        "next_step": "确认 SHFE 官方表格结构后接入解析器。",
    },
    "CN_XIAOBAODANG_MIXED_COAL_5500": {
        "status": "pending_source",
        "reason": "尚未找到稳定返回小保当 5500 大卡混煤历史价格的公开接口。",
        "next_step": "接入中国煤炭市场网数据库授权接口、矿方报价表或 Wind。",
    },
    "CN_HONGLIULIN_WASHED_MIDDLE_LUMP": {
        "status": "pending_source",
        "reason": "尚未找到稳定返回红柳林洗中块历史价格的公开接口。",
        "next_step": "接入中国煤炭市场网数据库授权接口、矿方报价表或 Wind。",
    },
    "CN_THERMAL_COAL_FUTURES_CLOSE": {
        "status": "pending_source",
        "reason": "郑商所动力煤主连公开行情停更在 2022-12，不能作为当前监控源。",
        "next_step": "接入郑商所授权数据、Wind 或交易所可持续历史行情。",
    },
    "CN_THERMAL_POWER_GENERATION": {
        "status": "pending_source",
        "reason": "当前未找到稳定公开接口返回全国火电发电量月度历史序列。",
        "next_step": "接入国家能源局、中电联、国家统计局稳定接口或 Wind 发电结构口径。",
    },
    "CN_HYDRO_POWER_GENERATION": {
        "status": "pending_source",
        "reason": "当前未找到稳定公开接口返回全国水电发电量月度历史序列。",
        "next_step": "接入国家能源局、中电联、国家统计局稳定接口或 Wind 发电结构口径。",
    },
    "CN_WIND_POWER_GENERATION": {
        "status": "pending_source",
        "reason": "当前未找到稳定公开接口返回全国风电发电量月度历史序列。",
        "next_step": "接入国家能源局、中电联、国家统计局稳定接口或 Wind 发电结构口径。",
    },
    "CN_SOLAR_POWER_GENERATION": {
        "status": "pending_source",
        "reason": "当前未找到稳定公开接口返回全国太阳能发电量月度历史序列。",
        "next_step": "接入国家能源局、中电联、国家统计局稳定接口或 Wind 发电结构口径。",
    },
    "CN_NUCLEAR_POWER_GENERATION": {
        "status": "pending_source",
        "reason": "当前未找到稳定公开接口返回全国核电发电量月度历史序列。",
        "next_step": "接入国家能源局、中电联、国家统计局稳定接口或 Wind 发电结构口径。",
    },
    "US_API_CRUDE_STOCK_CHANGE": {
        "status": "pending_source",
        "reason": "AkShare/Jin10 美国 API 原油库存变动序列当前停更在 2025-09，不能作为当前监控源。",
        "next_step": "接入 API 官方授权源，或改用可持续更新的 EIA/FRED 口径。",
    },
    "US_EIA_CRUDE_STOCK_CHANGE": {
        "status": "pending_source",
        "reason": "AkShare/Jin10 美国 EIA 原油库存变动序列当前停更在 2025-09，不能作为当前监控源。",
        "next_step": "配置 EIA_API_KEY 后接入官方 EIA weekly petroleum status 口径。",
    },
    **{
        f"{route}_TANKER_FREIGHT": {
            "status": "pending_source",
            "reason": (
                f"{route} 属于 Baltic Exchange 航线级油轮运价，"
                "未找到稳定免授权历史接口。"
            ),
            "next_step": (
                "接入 Baltic Exchange 授权数据、Clarksons/SSY/Braemar 授权源，"
                "或可审计内部油运数据库；中远海能、招商南油公开披露只作为校验参考。"
            ),
        }
        for route in (
            "TD3C",
            "TD7",
            "TD8",
            "TD9",
            "TD14",
            "TD15",
            "TD19",
            "TD20",
            "TD22",
            "TD25",
            "TC2",
            "TC5",
            "TC6",
            "TC8",
            "TC14",
            "TC17",
            "TC20",
        )
    },
}

INDICATOR_AVAILABILITY = {
    **UNAVAILABLE_SERIES,
    "CN_DEBT_TO_GDP": {
        "status": "no_data",
        "reason": "World Bank 对中国中央政府债务占 GDP 指标当前可访问但无可写入观测值。",
        "next_step": "接入财政部、IMF、BIS 或 Wind 的政府债务口径。",
    },
    "CN_FISCAL_BALANCE_TO_GDP": {
        "status": "no_data",
        "reason": "World Bank 对中国财政余额占 GDP 指标当前可访问但无可写入观测值。",
        "next_step": "接入财政部财政收支口径、IMF 或 Wind。",
    },
}
