import type { IndicatorDefinition, Observation } from "../types";

export type LocalizedIndicator = {
  name: string;
  description: string;
  unit: string;
  sourceLabel: string;
};

const wb = "世界银行";
const fred = "FRED";
const akEastmoney = "AkShare / 东方财富";
const akMarket = "AkShare / 行情源";
const pendingNbsWind = "国家统计局 / Wind 待接入";
const pendingPbocWind = "人民银行 / Wind 待接入";
const pendingCustomsWind = "海关总署 / Wind 待接入";
const cctd = "CCTD 中国煤炭市场网";
const cfdCoal = "曹妃甸煤贸数港";

const INDICATOR_LABELS: Record<string, LocalizedIndicator> = {
  US_DGS3MO: {
    name: "美国国债收益率 3M",
    description: "美国财政部官方日频国债收益率，短端主要反映政策利率路径和流动性预期。",
    unit: "%",
    sourceLabel: "美国财政部",
  },
  US_DGS2: {
    name: "美国国债收益率 2Y",
    description: "美国财政部官方日频国债收益率，2年期对货币政策预期更敏感。",
    unit: "%",
    sourceLabel: "美国财政部",
  },
  US_DGS5: {
    name: "美国国债收益率 5Y",
    description: "美国财政部官方日频国债收益率，适合观察中端实际利率和增长预期。",
    unit: "%",
    sourceLabel: "美国财政部",
  },
  US_DGS10: {
    name: "美国国债收益率 10Y",
    description: "美国财政部官方日频国债收益率，长端定价通胀、增长和期限溢价。",
    unit: "%",
    sourceLabel: "美国财政部",
  },
  US_DGS30: {
    name: "美国国债收益率 30Y",
    description: "美国财政部官方日频国债收益率，超长端用于观察期限溢价和财政供给压力。",
    unit: "%",
    sourceLabel: "美国财政部",
  },
  JP_LONG_RATE: { name: "日本长期国债收益率", description: "用于横向比较主要经济体长端利率。", unit: "%", sourceLabel: fred },
  DE_LONG_RATE: { name: "德国长期国债收益率", description: "用于观察欧洲核心利率变化。", unit: "%", sourceLabel: fred },
  EU_LONG_RATE: { name: "欧元区长期国债收益率", description: "用于观察欧洲整体长端利率。", unit: "%", sourceLabel: fred },
  US_GDP: { name: "美国名义 GDP", description: "衡量美国经济总量和周期趋势。", unit: "十亿美元", sourceLabel: fred },
  US_FEDERAL_DEBT: { name: "美国联邦债务规模", description: "用于观察美国财政杠杆。", unit: "百万美元", sourceLabel: fred },
  US_DEBT_TO_GDP: { name: "美国联邦债务 / GDP", description: "用于衡量债务负担。", unit: "%", sourceLabel: fred },
  US_FISCAL_BALANCE_TO_GDP: { name: "美国财政余额 / GDP", description: "负值代表财政赤字。", unit: "%", sourceLabel: fred },
  US_ISM_MANUFACTURING_PMI: { name: "美国 ISM 制造业 PMI", description: "用于观察美国制造业景气。", unit: "指数", sourceLabel: "AkShare / Jin10" },
  US_UNEMPLOYMENT_RATE: { name: "美国失业率", description: "用于观察劳动力市场松紧。", unit: "%", sourceLabel: "AkShare / Jin10" },
  US_NONFARM_PAYROLLS: { name: "美国非农就业变动", description: "用于观察美国新增就业动能。", unit: "万人", sourceLabel: "AkShare / Jin10" },
  US_CPI_YOY: { name: "美国 CPI 同比", description: "用于观察居民端通胀压力。", unit: "%", sourceLabel: akEastmoney },
  US_CORE_PCE_YOY: { name: "美国核心 PCE 年率", description: "用于观察美联储关注的通胀压力。", unit: "%", sourceLabel: "AkShare / Jin10" },
  US_RETAIL_SALES_MOM: { name: "美国零售销售月率", description: "用于观察消费需求动能。", unit: "%", sourceLabel: "AkShare / Jin10" },
  CN_GDP: { name: "中国名义 GDP（美元口径）", description: "世界银行年度现价美元 GDP。", unit: "美元", sourceLabel: wb },
  CN_NOMINAL_GDP_QUARTERLY: { name: "中国名义 GDP", description: "国家统计口径季度累计现价 GDP。", unit: "亿元", sourceLabel: akEastmoney },
  CN_REAL_GDP: { name: "中国实际 GDP", description: "需要国家统计局不变价序列或 Wind 接入，当前不写入模拟值。", unit: "指数 / 人民币", sourceLabel: pendingNbsWind },
  CN_REAL_GDP_GROWTH: { name: "中国实际 GDP 增速（年度）", description: "用于观察经济总量的真实增长。", unit: "%", sourceLabel: wb },
  CN_REAL_GDP_QUARTERLY_YOY: { name: "中国实际 GDP 增速", description: "GDP 不变价同比增速，用于观察实际增长。", unit: "%", sourceLabel: akEastmoney },
  CN_HOUSEHOLD_CONSUMPTION: { name: "居民最终消费支出", description: "用于观察消费对总需求的贡献。", unit: "美元", sourceLabel: wb },
  CN_RETAIL_SALES: { name: "社会消费品零售总额同比", description: "社零是国内消费修复的核心月度指标。", unit: "%", sourceLabel: akEastmoney },
  CN_GROSS_CAPITAL_FORMATION: { name: "资本形成总额", description: "用于观察投资和库存变动形成的需求。", unit: "美元", sourceLabel: wb },
  CN_INDUSTRY_VALUE_ADDED: { name: "工业增加值（年度）", description: "用于观察工业部门产出规模。", unit: "美元", sourceLabel: wb },
  CN_INDUSTRIAL_PRODUCTION_YOY: { name: "规模以上工业增加值同比", description: "用于跟踪工业生产景气。", unit: "%", sourceLabel: akEastmoney },
  CN_FIXED_ASSET_INVESTMENT: { name: "固定资产投资同比", description: "用于观察投资需求。", unit: "%", sourceLabel: akEastmoney },
  CN_MANUFACTURING_PMI: { name: "中国制造业 PMI", description: "用于观察制造业景气和订单变化。", unit: "指数", sourceLabel: akEastmoney },
  CN_NON_MANUFACTURING_PMI: { name: "中国非制造业 PMI", description: "用于观察服务业和建筑业景气。", unit: "指数", sourceLabel: akEastmoney },
  CN_MANUFACTURING_INVESTMENT: { name: "制造业投资", description: "制造业投资累计同比仍需稳定官方接口或 Wind。", unit: "%", sourceLabel: pendingNbsWind },
  CN_INFRASTRUCTURE_INVESTMENT: { name: "基建投资", description: "基建投资累计同比仍需稳定官方接口或 Wind。", unit: "%", sourceLabel: pendingNbsWind },
  CN_REAL_ESTATE_INVESTMENT: { name: "房地产开发投资", description: "房地产开发投资累计同比仍需稳定官方接口或 Wind。", unit: "%", sourceLabel: pendingNbsWind },
  CN_PROPERTY_SALES_AREA: { name: "商品房销售面积", description: "商品房销售面积累计同比仍需稳定官方接口或 Wind。", unit: "%", sourceLabel: pendingNbsWind },
  CN_NEW_HOME_PRICE_INDEX: { name: "新建商品住宅价格指数", description: "新房价格样本均值，用于观察房价变化。", unit: "指数", sourceLabel: akEastmoney },
  CN_EXPORTS_GOODS_SERVICES: { name: "货物和服务出口额", description: "用于观察外需和贸易景气。", unit: "美元", sourceLabel: wb },
  CN_IMPORTS_GOODS_SERVICES: { name: "货物和服务进口额", description: "用于观察内需和补库变化。", unit: "美元", sourceLabel: wb },
  CN_EXPORT_VALUE_USD: { name: "出口额（美元）", description: "海关总署口径当月出口额，用于观察外需规模。", unit: "亿美元", sourceLabel: "AkShare / 海关总署" },
  CN_IMPORT_VALUE_USD: { name: "进口额（美元）", description: "海关总署口径当月进口额，用于观察内需和补库规模。", unit: "亿美元", sourceLabel: "AkShare / 海关总署" },
  CN_EXPORT_YOY_USD: { name: "出口同比（美元）", description: "海关总署口径美元计出口同比，用于观察外需变化。", unit: "%", sourceLabel: "AkShare / 海关总署" },
  CN_IMPORT_YOY_USD: { name: "进口同比（美元）", description: "海关总署口径美元计进口同比，用于观察内需和补库变化。", unit: "%", sourceLabel: "AkShare / 海关总署" },
  CN_CPI_INFLATION: { name: "CPI 通胀率", description: "年度 CPI 通胀率，用于观察居民端价格压力。", unit: "%", sourceLabel: wb },
  CN_CPI_MONTHLY_YOY: { name: "CPI 同比", description: "国家统计口径 CPI 月度同比，用于观察居民端通胀压力。", unit: "%", sourceLabel: akEastmoney },
  CN_PPI: { name: "PPI 同比", description: "用于观察工业品出厂价格和企业盈利压力。", unit: "%", sourceLabel: akEastmoney },
  CN_CORPORATE_GOODS_PRICE_INDEX: { name: "企业商品价格指数", description: "用于观察上游和企业端价格压力。", unit: "指数", sourceLabel: akEastmoney },
  CN_EXPORT_PRICE_INDEX: { name: "出口价格指数", description: "出口价格指数仍需海关总署稳定接口或 Wind。", unit: "指数", sourceLabel: pendingCustomsWind },
  CN_IMPORT_PRICE_INDEX: { name: "进口价格指数", description: "进口价格指数仍需海关总署稳定接口或 Wind。", unit: "指数", sourceLabel: pendingCustomsWind },
  CN_TOTAL_SOCIAL_FINANCING: { name: "社会融资规模", description: "社会融资规模月度值，用于观察实体经济融资需求。", unit: "亿元", sourceLabel: akEastmoney },
  CN_RMB_LOANS: { name: "新增人民币贷款", description: "新增信贷当月值，用于观察信用投放强弱。", unit: "亿元", sourceLabel: akEastmoney },
  CN_M2: { name: "中国 M2", description: "广义货币供应量，反映总量流动性。", unit: "亿元", sourceLabel: akEastmoney },
  CN_M2_YOY: { name: "中国 M2 同比", description: "广义货币供应量同比增速，反映总量流动性扩张速度。", unit: "%", sourceLabel: akEastmoney },
  CN_M1: { name: "中国 M1", description: "狭义货币供应量，用于观察企业活期资金和交易活跃度。", unit: "亿元", sourceLabel: akEastmoney },
  CN_M1_YOY: { name: "中国 M1 同比", description: "狭义货币供应量同比增速，用于观察资金活化变化。", unit: "%", sourceLabel: akEastmoney },
  CN_M0: { name: "中国 M0", description: "流通中现金，用于观察现金需求。", unit: "亿元", sourceLabel: akEastmoney },
  CN_M0_YOY: { name: "中国 M0 同比", description: "流通中现金同比增速。", unit: "%", sourceLabel: akEastmoney },
  CN_M1_M2_SCISSORS: { name: "M1-M2 剪刀差", description: "M1 同比减 M2 同比，用于观察资金活化程度。", unit: "百分点", sourceLabel: akEastmoney },
  CN_OFFICIAL_EXCHANGE_RATE: { name: "人民币兑美元官方平均汇率", description: "年度官方平均汇率。", unit: "人民币/美元", sourceLabel: wb },
  CN_SHCOMP: { name: "上证综指", description: "用于观察国内金融市场风险偏好。", unit: "指数", sourceLabel: akMarket },
  US_EIA_CRUDE_STOCKS: { name: "美国商业原油库存", description: "EIA 周度原油库存，需要配置 EIA API Key 后接入。", unit: "千桶", sourceLabel: "EIA 待接入" },
  US_API_CRUDE_STOCK_CHANGE: { name: "美国 API 原油库存变动", description: "公开事件源停更在 2025-09，当前不作为可用监控数据。", unit: "万桶", sourceLabel: "API 授权源待接入" },
  US_EIA_CRUDE_STOCK_CHANGE: { name: "美国 EIA 原油库存变动", description: "公开事件源停更在 2025-09，等待 EIA API Key 后接入官方口径。", unit: "万桶", sourceLabel: "EIA 待接入" },
  US_CRUDE_OIL_PRODUCTION: { name: "美国原油产量", description: "美国国内原油周度产量，用于观察供应端变化。", unit: "万桶/日", sourceLabel: "AkShare / Jin10" },
  US_CRUDE_OIL_PRODUCTION_CHANGE: { name: "美国原油产量变化", description: "美国国内原油周度产量变化，用于观察供应边际变化。", unit: "万桶/日", sourceLabel: "AkShare / Jin10" },
  CN_GASOLINE_RETAIL_PRICE: { name: "国内汽油调价价格", description: "中国汽油调价价格，用于观察国内成品油价格传导。", unit: "元/吨", sourceLabel: akEastmoney },
  CN_DIESEL_RETAIL_PRICE: { name: "国内柴油调价价格", description: "中国柴油调价价格，用于观察国内成品油价格传导。", unit: "元/吨", sourceLabel: akEastmoney },
  BDTI_INDEX: { name: "BDTI 原油运输指数", description: "BDTI 原油运输指数，用于观察脏油轮运价。", unit: "指数", sourceLabel: akEastmoney },
  BCTI_INDEX: { name: "BCTI 成品油运输指数", description: "BCTI 成品油运输指数，用于观察成品油轮运价。", unit: "指数", sourceLabel: akEastmoney },
  BDI_INDEX: { name: "BDI 干散货指数", description: "BDI 波罗的海干散货指数，用于辅助观察全球海运景气。", unit: "指数", sourceLabel: akEastmoney },
  BCI_INDEX: { name: "BCI 好望角型船指数", description: "BCI 好望角型船指数，用于观察大船运价和大宗商品运输景气。", unit: "指数", sourceLabel: akEastmoney },
  BPI_INDEX: { name: "BPI 巴拿马型船指数", description: "BPI 巴拿马型船指数，用于观察中型散货船运价。", unit: "指数", sourceLabel: akEastmoney },
  TD3C_TANKER_FREIGHT: { name: "TD3C 中东至中国 VLCC", description: "航线级油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TD7_TANKER_FREIGHT: { name: "TD7 北海至欧洲 Aframax", description: "航线级油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TD8_TANKER_FREIGHT: { name: "TD8 科威特至新加坡 Aframax", description: "航线级油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TD9_TANKER_FREIGHT: { name: "TD9 加勒比至美湾 Aframax", description: "航线级油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TD14_TANKER_FREIGHT: { name: "TD14 东南亚至澳东 Aframax", description: "航线级油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TD15_TANKER_FREIGHT: { name: "TD15 西非至中国 Suezmax", description: "航线级油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TD19_TANKER_FREIGHT: { name: "TD19 地中海 Aframax", description: "航线级油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TD20_TANKER_FREIGHT: { name: "TD20 西非至欧洲油轮", description: "航线级油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TD22_TANKER_FREIGHT: { name: "TD22 美湾至中国 VLCC", description: "航线级油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TD25_TANKER_FREIGHT: { name: "TD25 美湾至欧洲 Aframax", description: "航线级油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TC2_TANKER_FREIGHT: { name: "TC2 欧洲至美东成品油轮", description: "航线级成品油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TC5_TANKER_FREIGHT: { name: "TC5 中东至日本 LR2", description: "航线级成品油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TC6_TANKER_FREIGHT: { name: "TC6 阿尔及利亚至地中海 MR", description: "航线级成品油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TC8_TANKER_FREIGHT: { name: "TC8 中东至欧洲 LR1", description: "航线级成品油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TC14_TANKER_FREIGHT: { name: "TC14 美湾至欧洲成品油轮", description: "航线级成品油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TC17_TANKER_FREIGHT: { name: "TC17 中东至东非 MR", description: "航线级成品油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  TC20_TANKER_FREIGHT: { name: "TC20 中东至欧洲 LR2", description: "航线级成品油轮运价需要 Baltic Exchange 或船舶经纪授权源，当前仅作待接入指标。", unit: "WS / 美元每吨", sourceLabel: "Baltic Exchange 待接入" },
  EIA_US_CRUDE_STOCKS_EX_SPR: { name: "EIA 商业原油库存", description: "美国商业原油库存（不含 SPR），用于观察商业库存和供需平衡。", unit: "千桶", sourceLabel: "EIA dnav" },
  EIA_US_TOTAL_CRUDE_STOCKS: { name: "EIA 原油总库存", description: "美国原油总库存（含 SPR），用于观察原油总体库存水位。", unit: "千桶", sourceLabel: "EIA dnav" },
  EIA_CUSHING_CRUDE_STOCKS: { name: "EIA 库欣原油库存", description: "库欣原油库存，用于观察 WTI 交割地库存压力。", unit: "千桶", sourceLabel: "EIA dnav" },
  EIA_US_SPR_CRUDE_STOCKS: { name: "EIA 战略储备库存", description: "美国战略石油储备库存，用于观察政策储备变化。", unit: "千桶", sourceLabel: "EIA dnav" },
  EIA_US_CRUDE_PRODUCTION: { name: "EIA 美国原油产量", description: "EIA 美国原油周度产量，用于观察供应端变化。", unit: "千桶/日", sourceLabel: "EIA dnav" },
  EIA_LOWER48_CRUDE_PRODUCTION: { name: "EIA 本土48州原油产量", description: "EIA 美国本土 48 州原油周度产量，用于剔除阿拉斯加后的供应观察。", unit: "千桶/日", sourceLabel: "EIA dnav" },
  EIA_US_CRUDE_IMPORTS: { name: "EIA 美国原油进口", description: "美国原油进口量，用于观察外部供给和炼厂采购。", unit: "千桶/日", sourceLabel: "EIA dnav" },
  EIA_US_CRUDE_EXPORTS: { name: "EIA 美国原油出口", description: "美国原油出口量，用于观察出口套利和全球流向。", unit: "千桶/日", sourceLabel: "EIA dnav" },
  EIA_US_REFINERY_CRUDE_INPUTS: { name: "EIA 炼厂原油投入", description: "美国炼厂原油净投入，用于观察炼厂需求。", unit: "千桶/日", sourceLabel: "EIA dnav" },
  EIA_US_REFINERY_UTILIZATION: { name: "EIA 炼厂开工率", description: "美国炼厂开工率，用于观察炼化负荷。", unit: "%", sourceLabel: "EIA dnav" },
  EIA_US_TOTAL_GASOLINE_STOCKS: { name: "EIA 汽油库存", description: "美国汽油库存，用于观察成品油供需。", unit: "千桶", sourceLabel: "EIA dnav" },
  EIA_US_DISTILLATE_STOCKS: { name: "EIA 馏分油库存", description: "美国馏分油库存，用于观察柴油和取暖油供需。", unit: "千桶", sourceLabel: "EIA dnav" },
  EIA_US_JET_FUEL_STOCKS: { name: "EIA 航煤库存", description: "美国航煤库存，用于观察航空燃料供需。", unit: "千桶", sourceLabel: "EIA dnav" },
  EIA_US_TOTAL_PETROLEUM_STOCKS: { name: "EIA 全油品库存", description: "美国原油及石油产品总库存，用于观察全油品库存水位。", unit: "千桶", sourceLabel: "EIA dnav" },
  LME_COPPER_INVENTORY: { name: "LME 铜库存", description: "海外铜显性库存，用于观察有色供需变化。", unit: "吨", sourceLabel: "AkShare / LME" },
  LME_ALUMINUM_INVENTORY: { name: "LME 铝库存", description: "海外铝显性库存，用于观察轻金属供需变化。", unit: "吨", sourceLabel: "AkShare / LME" },
  LME_ZINC_INVENTORY: { name: "LME 锌库存", description: "海外锌显性库存，用于观察镀锌和基建链条变化。", unit: "吨", sourceLabel: "AkShare / LME" },
  LME_NICKEL_INVENTORY: { name: "LME 镍库存", description: "海外镍显性库存，用于观察不锈钢和新能源材料链变化。", unit: "吨", sourceLabel: "AkShare / LME" },
  COMEX_GOLD_INVENTORY: { name: "COMEX 黄金库存", description: "COMEX 黄金库存，用于补充观察贵金属显性库存。", unit: "吨", sourceLabel: "AkShare / COMEX" },
  SHFE_COPPER_INVENTORY: { name: "上期所铜库存", description: "国内铜显性库存，用于观察国内有色库存变化。", unit: "吨", sourceLabel: "AkShare / 东方财富" },
  JP_GDP: { name: "日本名义 GDP", description: "日本现价美元 GDP。", unit: "美元", sourceLabel: wb },
  EU_GDP: { name: "欧元区名义 GDP", description: "欧元区现价美元 GDP。", unit: "美元", sourceLabel: wb },
  CN_DEBT_TO_GDP: { name: "中国政府债务 / GDP", description: "用于观察财政杠杆。", unit: "%", sourceLabel: wb },
  JP_DEBT_TO_GDP: { name: "日本政府债务 / GDP", description: "用于观察债务负担。", unit: "%", sourceLabel: wb },
  EU_DEBT_TO_GDP: { name: "欧元区政府债务 / GDP", description: "用于观察债务负担。", unit: "%", sourceLabel: wb },
  CN_FISCAL_BALANCE_TO_GDP: { name: "中国财政余额 / GDP", description: "负值代表财政赤字。", unit: "%", sourceLabel: wb },
  JP_FISCAL_BALANCE_TO_GDP: { name: "日本财政余额 / GDP", description: "负值代表财政赤字。", unit: "%", sourceLabel: wb },
  EU_FISCAL_BALANCE_TO_GDP: { name: "欧元区财政余额 / GDP", description: "负值代表财政赤字。", unit: "%", sourceLabel: wb },
  CU_PRICE: { name: "铜价", description: "全球铜价，用于观察工业需求和制造业景气。", unit: "美元/吨", sourceLabel: fred },
  AL_PRICE: { name: "铝价", description: "全球铝价，用于观察轻金属供需。", unit: "美元/吨", sourceLabel: fred },
  NI_PRICE: { name: "镍价", description: "全球镍价，用于跟踪不锈钢和新能源材料链。", unit: "美元/吨", sourceLabel: fred },
  ZN_PRICE: { name: "锌价", description: "全球锌价，用于观察镀锌和基建需求。", unit: "美元/吨", sourceLabel: fred },
  PB_PRICE: { name: "铅价", description: "全球铅价，用于观察蓄电池和工业需求。", unit: "美元/吨", sourceLabel: fred },
  IRON_ORE_PRICE: { name: "铁矿石价格", description: "用于观察黑色链条和工业原料需求。", unit: "美元/干吨", sourceLabel: fred },
  OIL_BRENT_PRICE: { name: "Brent 原油", description: "Brent 现货价格，用于观察全球原油定价。", unit: "美元/桶", sourceLabel: fred },
  OIL_WTI_PRICE: { name: "WTI 原油", description: "WTI 现货价格，用于观察美国原油定价。", unit: "美元/桶", sourceLabel: fred },
  US_GASOLINE_PRICE: { name: "美国汽油零售价", description: "用于观察成品油终端价格。", unit: "美元/加仑", sourceLabel: fred },
  EU_NATURAL_GAS_PRICE: { name: "欧洲天然气价格", description: "用于观察能源链价格压力。", unit: "美元/MMBtu", sourceLabel: fred },
  COAL_AUSTRALIA_PRICE: { name: "澳洲动力煤价格", description: "用于观察海运动力煤基准变化。", unit: "美元/吨", sourceLabel: fred },
  CCTD_HUANGLING_QI_COAL: { name: "黄陵气精煤价格", description: "CCTD 延安（黄陵）气精煤价格。", unit: "元/吨", sourceLabel: cctd },
  CCTD_QHD_THERMAL_COAL_5500: { name: "秦皇岛动力煤 5500", description: "CCTD 秦皇岛动力煤 5500 大卡综合交易价。", unit: "元/吨", sourceLabel: cctd },
  CCTD_QHD_THERMAL_COAL_5000: { name: "秦皇岛动力煤 5000", description: "CCTD 秦皇岛动力煤 5000 大卡综合交易价。", unit: "元/吨", sourceLabel: cctd },
  CCTD_QHD_THERMAL_COAL_4500: { name: "秦皇岛动力煤 4500", description: "CCTD 秦皇岛动力煤 4500 大卡综合交易价。", unit: "元/吨", sourceLabel: cctd },
  CCTD_TANGSHAN_COKING_COAL: { name: "唐山主焦煤价格", description: "CCTD 唐山主焦煤价格。", unit: "元/吨", sourceLabel: cctd },
  CCTD_TANGSHAN_FAT_COAL: { name: "唐山肥煤价格", description: "CCTD 唐山肥煤价格。", unit: "元/吨", sourceLabel: cctd },
  CCTD_ORIGIN_SHANXI_THERMAL_COAL_5500: { name: "山西产地动力煤 5500", description: "CCTD 产地动力煤山西 5500 大卡价格。", unit: "元/吨", sourceLabel: cctd },
  CFD_TTCI_THERMAL_COAL_5500: { name: "曹妃甸 TTCI 5500", description: "唐山动力煤 5500K 现货价格。", unit: "元/吨", sourceLabel: cfdCoal },
  CFD_TTCI_THERMAL_COAL_5000: { name: "曹妃甸 TTCI 5000", description: "唐山动力煤 5000K 现货价格。", unit: "元/吨", sourceLabel: cfdCoal },
  CFD_TTCI_THERMAL_COAL_4500: { name: "曹妃甸 TTCI 4500", description: "唐山动力煤 4500K 现货价格。", unit: "元/吨", sourceLabel: cfdCoal },
  CFD_TTCI_INDEX: { name: "TTCI 唐山动力煤指数", description: "曹妃甸 TTCI 唐山动力煤现货价格指数。", unit: "指数", sourceLabel: cfdCoal },
  CFD_TOFI_INDEX: { name: "TOFI 唐山海运煤炭运价指数", description: "曹妃甸 TOFI 唐山海运煤炭运价指数。", unit: "指数", sourceLabel: cfdCoal },
  CN_COKING_COAL_FUTURES_CLOSE: { name: "焦煤主连收盘价", description: "焦煤主连收盘价，用于观察焦煤期货市场预期。", unit: "元/吨", sourceLabel: "AkShare / 新浪期货" },
  CN_COKING_COAL_FUTURES_SETTLE: { name: "焦煤主连结算价", description: "焦煤主连结算价，用于观察焦煤期货定价。", unit: "元/吨", sourceLabel: "AkShare / 新浪期货" },
  CN_COKE_FUTURES_CLOSE: { name: "焦炭主连收盘价", description: "焦炭主连收盘价，用于观察焦化利润和钢厂需求预期。", unit: "元/吨", sourceLabel: "AkShare / 新浪期货" },
  CN_COKE_FUTURES_SETTLE: { name: "焦炭主连结算价", description: "焦炭主连结算价，用于观察焦炭期货定价。", unit: "元/吨", sourceLabel: "AkShare / 新浪期货" },
  CN_COKING_COAL_99QH_INVENTORY: { name: "焦煤 99期货库存", description: "99 期货网焦煤库存，用于观察交易所相关库存变化。", unit: "吨", sourceLabel: "AkShare / 99期货" },
  CN_COKE_99QH_INVENTORY: { name: "焦炭 99期货库存", description: "99 期货网焦炭库存，用于观察焦炭库存变化。", unit: "吨", sourceLabel: "AkShare / 99期货" },
  CN_METHANOL_99QH_INVENTORY: { name: "甲醇 99期货库存", description: "99 期货网甲醇库存，用于补充观察煤化工链条。", unit: "吨", sourceLabel: "AkShare / 99期货" },
  CN_XIAOBAODANG_MIXED_COAL_5500: { name: "小保当 5500 混煤", description: "尚未找到稳定公开历史接口，等待 CCTD 数据库授权、矿方报价表或 Wind。", unit: "元/吨", sourceLabel: "CCTD / Wind 待接入" },
  CN_HONGLIULIN_WASHED_MIDDLE_LUMP: { name: "红柳林洗中块", description: "尚未找到稳定公开历史接口，等待 CCTD 数据库授权、矿方报价表或 Wind。", unit: "元/吨", sourceLabel: "CCTD / Wind 待接入" },
  CN_THERMAL_COAL_FUTURES_CLOSE: { name: "动力煤主连收盘价", description: "郑商所动力煤主连公开行情停更在 2022-12，不能作为当前监控源。", unit: "元/吨", sourceLabel: "郑商所 / Wind 待接入" },
  US_POWER_PRODUCTION: { name: "美国电力生产指数", description: "用于观察电力需求和工业活动。", unit: "指数", sourceLabel: fred },
  CN_SOCIETY_ELECTRICITY: { name: "全社会用电量", description: "中国全社会用电量，用于观察实体经济活动和电力需求。", unit: "亿千瓦时", sourceLabel: "AkShare / 新浪财经" },
  CN_SOCIETY_ELECTRICITY_YOY: { name: "全社会用电量同比", description: "中国全社会用电量同比，用于观察实体经济用电强弱。", unit: "%", sourceLabel: "AkShare / 新浪财经" },
  CN_ENERGY_INDEX: { name: "中国能源指数", description: "用于观察能源板块景气和风险偏好。", unit: "指数", sourceLabel: akEastmoney },
};

const SELECTOR_VALUE_LABELS: Record<string, string> = {
  "United States": "美国",
  Japan: "日本",
  Germany: "德国",
  "Euro Area": "欧元区",
  China: "中国",
  Global: "全球",
  Europe: "欧洲",
  Yield: "收益率",
  GDP: "名义 GDP",
  Debt: "债务规模",
  "Debt/GDP": "债务/GDP",
  "Fiscal balance": "财政余额",
  "ISM PMI": "ISM PMI",
  "CPI同比": "CPI 同比",
  "核心PCE": "核心 PCE",
  "失业率": "失业率",
  "非农就业": "非农就业",
  "零售销售": "零售销售",
  Price: "价格",
  "Crude price": "原油价格",
  "Product price": "成品油价格",
  "Gas price": "天然气价格",
  Production: "生产指数",
  Copper: "铜",
  Aluminum: "铝",
  Nickel: "镍",
  Gold: "黄金",
  Zinc: "锌",
  Lead: "铅",
  "Iron ore": "铁矿石",
  Inventory: "库存",
  "Crude oil": "原油",
  LME: "LME",
  COMEX: "COMEX",
  SHFE: "上期所",
  Brent: "Brent",
  WTI: "WTI",
  Gasoline: "汽油",
  "Natural gas": "天然气",
  "Thermal coal": "动力煤",
  CCTD: "CCTD",
  "曹妃甸": "曹妃甸",
  "矿口": "矿口",
  "黄陵气精煤": "黄陵气精煤",
  "秦皇岛5500": "秦皇岛 5500",
  "秦皇岛5000": "秦皇岛 5000",
  "秦皇岛4500": "秦皇岛 4500",
  "唐山主焦煤": "唐山主焦煤",
  "唐山肥煤": "唐山肥煤",
  "山西5500": "山西 5500",
  TTCI5500: "TTCI 5500",
  TTCI5000: "TTCI 5000",
  TTCI4500: "TTCI 4500",
  "TTCI指数": "TTCI 指数",
  "TOFI指数": "TOFI 指数",
  "大商所": "大商所",
  "郑商所": "郑商所",
  "99期货": "99期货",
  "焦煤期货收盘": "焦煤期货收盘",
  "焦煤期货结算": "焦煤期货结算",
  "焦炭期货收盘": "焦炭期货收盘",
  "焦炭期货结算": "焦炭期货结算",
  "焦煤库存": "焦煤库存",
  "焦炭库存": "焦炭库存",
  "甲醇库存": "甲醇库存",
  "动力煤期货": "动力煤期货",
  "小保当5500混煤": "小保当 5500 混煤",
  "红柳林洗中块": "红柳林洗中块",
  "Long-term": "长期",
  "就业与消费": "就业与消费",
  "价格": "价格",
  "Stock change": "库存变动",
  "EIA stock change": "EIA 库存变动",
  "Production change": "产量变化",
  "Retail guide price": "调价价格",
  Diesel: "柴油",
  "Baltic Exchange": "波罗的海交易所",
  "Dirty tanker": "原油运输",
  "Clean tanker": "成品油运输",
  "Dry bulk": "干散货",
  Capesize: "好望角型船",
  Panamax: "巴拿马型船",
  BDTI: "BDTI",
  BCTI: "BCTI",
  BDI: "BDI",
  BCI: "BCI",
  BPI: "BPI",
  TD3C: "TD3C",
  TD7: "TD7",
  TD8: "TD8",
  TD9: "TD9",
  TD14: "TD14",
  TD15: "TD15",
  TD19: "TD19",
  TD20: "TD20",
  TD22: "TD22",
  TD25: "TD25",
  TC2: "TC2",
  TC5: "TC5",
  TC6: "TC6",
  TC8: "TC8",
  TC14: "TC14",
  TC17: "TC17",
  TC20: "TC20",
  EIA: "EIA",
  "Cushing inventory": "库欣库存",
  "SPR inventory": "战略储备库存",
  "Lower 48 production": "本土48州产量",
  Imports: "进口",
  Exports: "出口",
  "Refinery input": "炼厂投入",
  "Refinery utilization": "炼厂开工率",
  "Gasoline stocks": "汽油库存",
  "Distillate stocks": "馏分油库存",
  "Jet fuel stocks": "航煤库存",
  "Total petroleum stocks": "全油品库存",
  "Electricity consumption": "用电量",
  "Electricity consumption YoY": "用电量同比",
  "Energy index": "能源指数",
};

export function localizeIndicator(definition: IndicatorDefinition): LocalizedIndicator {
  return (
    INDICATOR_LABELS[definition.code] ?? {
      name: definition.name,
      description: definition.description,
      unit: definition.unit,
      sourceLabel: definition.provider,
    }
  );
}

export function localizeIndicatorCode(code: string): string {
  return INDICATOR_LABELS[code]?.name ?? code;
}

export function localizeSelectorValue(value: string): string {
  return SELECTOR_VALUE_LABELS[value] ?? value;
}

export function selectorSummary(definition: IndicatorDefinition): string {
  return Object.values(definition.selectors).map(localizeSelectorValue).join(" / ") || definition.region;
}

export function latestInRange(points: Observation[]): Observation | null {
  return points.length > 0 ? points[points.length - 1] : null;
}
