"""宏观指标目录。"""

from backend.constant import (
    AKSHARE_CHINA_SERIES,
    ASKCI_PUBLIC_SERIES,
    COAL_PUBLIC_SERIES,
    EIA_PUBLIC_SERIES,
    FRED_SERIES,
    INDICATOR_AVAILABILITY,
    NEA_PUBLIC_SERIES,
    US_TREASURY_SERIES,
    WORLD_BANK_SERIES,
)
from backend.domain.models import Frequency, IndicatorDefinition

_TREASURY_NAMES = {
    "US_DGS3MO": ("U.S. Treasury 3M yield", "3M"),
    "US_DGS2": ("U.S. Treasury 2Y yield", "2Y"),
    "US_DGS5": ("U.S. Treasury 5Y yield", "5Y"),
    "US_DGS10": ("U.S. Treasury 10Y yield", "10Y"),
    "US_DGS30": ("U.S. Treasury 30Y yield", "30Y"),
}


def _indicator(
    *,
    code: str,
    name: str,
    domain: str,
    region: str,
    unit: str,
    frequency: Frequency,
    provider: str,
    source: str,
    description: str,
    display_order: int,
    selectors: dict[str, str],
    availability: dict[str, str] | None = None,
) -> IndicatorDefinition:
    return IndicatorDefinition(
        code=code,
        name=name,
        domain=domain,
        region=region,
        unit=unit,
        frequency=frequency,
        provider=provider,
        source=source,
        description=description,
        display_order=display_order,
        selectors=selectors,
        availability=availability or {},
    )


def _availability_for(code: str) -> dict[str, str] | None:
    metadata = INDICATOR_AVAILABILITY.get(code)
    if metadata is None:
        return None
    return {
        "status": metadata["status"],
        "reason": metadata["reason"],
        "next_step": metadata["next_step"],
    }


def _treasury_indicators() -> list[IndicatorDefinition]:
    """生成 FRED 美国国债收益率指标定义。"""

    indicators: list[IndicatorDefinition] = []
    for display_order, (code, treasury_column) in enumerate(US_TREASURY_SERIES.items(), start=1):
        name, tenor = _TREASURY_NAMES[code]
        indicators.append(
            _indicator(
                code=code,
                name=name,
                domain="rates",
                region="United States",
                unit="%",
                frequency="daily",
                provider="us_treasury",
                source=f"U.S. Treasury Daily Treasury Rates:{treasury_column}",
                description="美国国债收益率，用于观察美元利率曲线和市场风险偏好。",
                display_order=display_order,
                selectors={"country": "United States", "tenor": tenor, "metric": "Yield"},
            )
        )
    return indicators


_FRED_INDICATORS = [
    _indicator(
        code="JP_LONG_RATE",
        name="Japan long-term government bond yield",
        domain="rates",
        region="Japan",
        unit="%",
        frequency="monthly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['JP_LONG_RATE']}",
        description="日本长期政府债券收益率，用于横向比较主要经济体长端利率。",
        display_order=11,
        selectors={"country": "Japan", "tenor": "Long-term", "metric": "Yield"},
    ),
    _indicator(
        code="DE_LONG_RATE",
        name="Germany long-term government bond yield",
        domain="rates",
        region="Germany",
        unit="%",
        frequency="monthly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['DE_LONG_RATE']}",
        description="德国长期政府债券收益率，用于观察欧洲核心利率变化。",
        display_order=12,
        selectors={"country": "Germany", "tenor": "Long-term", "metric": "Yield"},
    ),
    _indicator(
        code="EU_LONG_RATE",
        name="Euro Area long-term government bond yield",
        domain="rates",
        region="Euro Area",
        unit="%",
        frequency="monthly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['EU_LONG_RATE']}",
        description="欧元区长期政府债券收益率，用于观察欧洲整体长端利率。",
        display_order=13,
        selectors={"country": "Euro Area", "tenor": "Long-term", "metric": "Yield"},
    ),
    _indicator(
        code="US_GDP",
        name="U.S. GDP",
        domain="country_macro",
        region="United States",
        unit="USD bn",
        frequency="quarterly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['US_GDP']}",
        description="美国名义 GDP，用于观察美国经济总量变化。",
        display_order=101,
        selectors={"country": "United States", "metric": "GDP"},
    ),
    _indicator(
        code="US_FEDERAL_DEBT",
        name="U.S. federal debt",
        domain="country_macro",
        region="United States",
        unit="USD mn",
        frequency="quarterly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['US_FEDERAL_DEBT']}",
        description="美国联邦政府债务规模，用于衡量财政杠杆变化。",
        display_order=102,
        selectors={"country": "United States", "metric": "Debt"},
    ),
    _indicator(
        code="US_DEBT_TO_GDP",
        name="U.S. federal debt to GDP",
        domain="country_macro",
        region="United States",
        unit="%",
        frequency="quarterly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['US_DEBT_TO_GDP']}",
        description="美国联邦债务占 GDP 比重，用于观察债务负担。",
        display_order=103,
        selectors={"country": "United States", "metric": "Debt/GDP"},
    ),
    _indicator(
        code="US_FISCAL_BALANCE_TO_GDP",
        name="U.S. fiscal balance to GDP",
        domain="country_macro",
        region="United States",
        unit="%",
        frequency="annual",
        provider="fred",
        source=f"FRED:{FRED_SERIES['US_FISCAL_BALANCE_TO_GDP']}",
        description="美国财政余额占 GDP 比重，负值代表财政赤字。",
        display_order=104,
        selectors={"country": "United States", "metric": "Fiscal balance"},
    ),
    _indicator(
        code="CU_PRICE",
        name="Copper price",
        domain="nonferrous",
        region="Global",
        unit="USD/tonne",
        frequency="monthly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['CU_PRICE']}",
        description="全球铜价格，用于观察有色金属需求与制造业景气。",
        display_order=301,
        selectors={"commodity": "Copper", "metric": "Price"},
    ),
    _indicator(
        code="AL_PRICE",
        name="Aluminum price",
        domain="nonferrous",
        region="Global",
        unit="USD/tonne",
        frequency="monthly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['AL_PRICE']}",
        description="全球铝价格，用于观察轻金属供需变化。",
        display_order=302,
        selectors={"commodity": "Aluminum", "metric": "Price"},
    ),
    _indicator(
        code="NI_PRICE",
        name="Nickel price",
        domain="nonferrous",
        region="Global",
        unit="USD/tonne",
        frequency="monthly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['NI_PRICE']}",
        description="全球镍价格，用于跟踪不锈钢和新能源材料链条。",
        display_order=303,
        selectors={"commodity": "Nickel", "metric": "Price"},
    ),
    _indicator(
        code="ZN_PRICE",
        name="Zinc price",
        domain="nonferrous",
        region="Global",
        unit="USD/tonne",
        frequency="monthly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['ZN_PRICE']}",
        description="全球锌价格，用于观察镀锌和基建需求变化。",
        display_order=304,
        selectors={"commodity": "Zinc", "metric": "Price"},
    ),
    _indicator(
        code="PB_PRICE",
        name="Lead price",
        domain="nonferrous",
        region="Global",
        unit="USD/tonne",
        frequency="monthly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['PB_PRICE']}",
        description="全球铅价格，用于观察蓄电池和工业需求变化。",
        display_order=305,
        selectors={"commodity": "Lead", "metric": "Price"},
    ),
    _indicator(
        code="IRON_ORE_PRICE",
        name="Iron ore price",
        domain="nonferrous",
        region="Global",
        unit="USD/dmtu",
        frequency="monthly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['IRON_ORE_PRICE']}",
        description="铁矿石价格，用于观察黑色与工业原料需求。",
        display_order=306,
        selectors={"commodity": "Iron ore", "metric": "Price"},
    ),
    _indicator(
        code="OIL_BRENT_PRICE",
        name="Brent crude oil price",
        domain="crude_oil",
        region="Global",
        unit="USD/bbl",
        frequency="daily",
        provider="fred",
        source=f"FRED:{FRED_SERIES['OIL_BRENT_PRICE']}",
        description="布伦特原油现货价格，用于跟踪全球原油定价。",
        display_order=401,
        selectors={"commodity": "Brent", "metric": "Crude price"},
    ),
    _indicator(
        code="OIL_WTI_PRICE",
        name="WTI crude oil price",
        domain="crude_oil",
        region="United States",
        unit="USD/bbl",
        frequency="daily",
        provider="fred",
        source=f"FRED:{FRED_SERIES['OIL_WTI_PRICE']}",
        description="WTI 原油现货价格，用于跟踪美国原油定价。",
        display_order=402,
        selectors={"commodity": "WTI", "metric": "Crude price"},
    ),
    _indicator(
        code="US_GASOLINE_PRICE",
        name="U.S. regular gasoline price",
        domain="crude_oil",
        region="United States",
        unit="USD/gal",
        frequency="weekly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['US_GASOLINE_PRICE']}",
        description="美国普通汽油零售价，用于观察成品油终端价格。",
        display_order=403,
        selectors={"commodity": "Gasoline", "metric": "Product price"},
    ),
    _indicator(
        code="EU_NATURAL_GAS_PRICE",
        name="Europe natural gas price",
        domain="crude_oil",
        region="Europe",
        unit="USD/MMBtu",
        frequency="monthly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['EU_NATURAL_GAS_PRICE']}",
        description="欧洲天然气价格，用于观察能源链条价格压力。",
        display_order=404,
        selectors={"commodity": "Natural gas", "metric": "Gas price"},
    ),
    _indicator(
        code="COAL_AUSTRALIA_PRICE",
        name="Australia coal price",
        domain="coal",
        region="Global",
        unit="USD/tonne",
        frequency="monthly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['COAL_AUSTRALIA_PRICE']}",
        description="澳大利亚煤炭价格，用于观察海运动力煤基准变化。",
        display_order=501,
        selectors={"commodity": "Thermal coal", "metric": "Price"},
    ),
    _indicator(
        code="US_POWER_PRODUCTION",
        name="U.S. electric power generation index",
        domain="power",
        region="United States",
        unit="index",
        frequency="monthly",
        provider="fred",
        source=f"FRED:{FRED_SERIES['US_POWER_PRODUCTION']}",
        description="美国电力生产指数，用于观察电力需求和工业活动。",
        display_order=601,
        selectors={"country": "United States", "metric": "Production"},
    ),
]

_COAL_PUBLIC_INDICATORS = [
    _indicator(
        code="CCTD_HUANGLING_QI_COAL",
        name="CCTD Huangling gas coal price",
        domain="coal",
        region="China",
        unit="CNY/tonne",
        frequency="weekly",
        provider="coal_public",
        source=COAL_PUBLIC_SERIES["CCTD_HUANGLING_QI_COAL"]["source"],
        description="CCTD 延安（黄陵）气精煤价格，用于观察陕西焦煤链条价格。",
        display_order=510,
        selectors={"country": "China", "market": "CCTD", "metric": "黄陵气精煤"},
    ),
    _indicator(
        code="CCTD_QHD_THERMAL_COAL_5500",
        name="CCTD Qinhuangdao thermal coal 5500",
        domain="coal",
        region="China",
        unit="CNY/tonne",
        frequency="weekly",
        provider="coal_public",
        source=COAL_PUBLIC_SERIES["CCTD_QHD_THERMAL_COAL_5500"]["source"],
        description="CCTD 秦皇岛动力煤 5500 大卡综合交易价。",
        display_order=511,
        selectors={"country": "China", "market": "CCTD", "metric": "秦皇岛5500"},
    ),
    _indicator(
        code="CCTD_QHD_THERMAL_COAL_5000",
        name="CCTD Qinhuangdao thermal coal 5000",
        domain="coal",
        region="China",
        unit="CNY/tonne",
        frequency="weekly",
        provider="coal_public",
        source=COAL_PUBLIC_SERIES["CCTD_QHD_THERMAL_COAL_5000"]["source"],
        description="CCTD 秦皇岛动力煤 5000 大卡综合交易价。",
        display_order=512,
        selectors={"country": "China", "market": "CCTD", "metric": "秦皇岛5000"},
    ),
    _indicator(
        code="CCTD_QHD_THERMAL_COAL_4500",
        name="CCTD Qinhuangdao thermal coal 4500",
        domain="coal",
        region="China",
        unit="CNY/tonne",
        frequency="weekly",
        provider="coal_public",
        source=COAL_PUBLIC_SERIES["CCTD_QHD_THERMAL_COAL_4500"]["source"],
        description="CCTD 秦皇岛动力煤 4500 大卡综合交易价。",
        display_order=513,
        selectors={"country": "China", "market": "CCTD", "metric": "秦皇岛4500"},
    ),
    _indicator(
        code="CCTD_TANGSHAN_COKING_COAL",
        name="CCTD Tangshan coking coal price",
        domain="coal",
        region="China",
        unit="CNY/tonne",
        frequency="weekly",
        provider="coal_public",
        source=COAL_PUBLIC_SERIES["CCTD_TANGSHAN_COKING_COAL"]["source"],
        description="CCTD 唐山主焦煤价格，用于观察焦煤价格变化。",
        display_order=514,
        selectors={"country": "China", "market": "CCTD", "metric": "唐山主焦煤"},
    ),
    _indicator(
        code="CCTD_TANGSHAN_FAT_COAL",
        name="CCTD Tangshan fat coal price",
        domain="coal",
        region="China",
        unit="CNY/tonne",
        frequency="weekly",
        provider="coal_public",
        source=COAL_PUBLIC_SERIES["CCTD_TANGSHAN_FAT_COAL"]["source"],
        description="CCTD 唐山肥煤价格，用于观察焦煤配煤价格变化。",
        display_order=515,
        selectors={"country": "China", "market": "CCTD", "metric": "唐山肥煤"},
    ),
    _indicator(
        code="CCTD_ORIGIN_SHANXI_THERMAL_COAL_5500",
        name="CCTD Shanxi origin thermal coal 5500",
        domain="coal",
        region="China",
        unit="CNY/tonne",
        frequency="monthly",
        provider="coal_public",
        source=COAL_PUBLIC_SERIES["CCTD_ORIGIN_SHANXI_THERMAL_COAL_5500"]["source"],
        description="CCTD 产地动力煤山西 5500 大卡价格。",
        display_order=516,
        selectors={"country": "China", "market": "CCTD", "metric": "山西5500"},
    ),
    _indicator(
        code="CFD_TTCI_THERMAL_COAL_5500",
        name="TTCI Tangshan thermal coal spot 5500",
        domain="coal",
        region="China",
        unit="CNY/tonne",
        frequency="daily",
        provider="coal_public",
        source=COAL_PUBLIC_SERIES["CFD_TTCI_THERMAL_COAL_5500"]["source"],
        description="曹妃甸煤贸数港 TTCI 唐山动力煤 5500K 现货价格。",
        display_order=517,
        selectors={"country": "China", "market": "曹妃甸", "metric": "TTCI5500"},
    ),
    _indicator(
        code="CFD_TTCI_THERMAL_COAL_5000",
        name="TTCI Tangshan thermal coal spot 5000",
        domain="coal",
        region="China",
        unit="CNY/tonne",
        frequency="daily",
        provider="coal_public",
        source=COAL_PUBLIC_SERIES["CFD_TTCI_THERMAL_COAL_5000"]["source"],
        description="曹妃甸煤贸数港 TTCI 唐山动力煤 5000K 现货价格。",
        display_order=518,
        selectors={"country": "China", "market": "曹妃甸", "metric": "TTCI5000"},
    ),
    _indicator(
        code="CFD_TTCI_THERMAL_COAL_4500",
        name="TTCI Tangshan thermal coal spot 4500",
        domain="coal",
        region="China",
        unit="CNY/tonne",
        frequency="daily",
        provider="coal_public",
        source=COAL_PUBLIC_SERIES["CFD_TTCI_THERMAL_COAL_4500"]["source"],
        description="曹妃甸煤贸数港 TTCI 唐山动力煤 4500K 现货价格。",
        display_order=519,
        selectors={"country": "China", "market": "曹妃甸", "metric": "TTCI4500"},
    ),
    _indicator(
        code="CFD_TTCI_INDEX",
        name="TTCI Tangshan thermal coal spot index",
        domain="coal",
        region="China",
        unit="index",
        frequency="daily",
        provider="coal_public",
        source=COAL_PUBLIC_SERIES["CFD_TTCI_INDEX"]["source"],
        description="曹妃甸煤贸数港 TTCI 唐山动力煤现货价格指数。",
        display_order=520,
        selectors={"country": "China", "market": "曹妃甸", "metric": "TTCI指数"},
    ),
    _indicator(
        code="CFD_TOFI_INDEX",
        name="Tangshan Ocean Freight Index",
        domain="coal",
        region="China",
        unit="index",
        frequency="daily",
        provider="coal_public",
        source=COAL_PUBLIC_SERIES["CFD_TOFI_INDEX"]["source"],
        description="曹妃甸煤贸数港 TOFI 唐山海运煤炭运价指数。",
        display_order=521,
        selectors={"country": "China", "market": "曹妃甸", "metric": "TOFI指数"},
    ),
]

_COAL_AKSHARE_INDICATOR_SPECS = [
    (
        "CN_COKING_COAL_FUTURES_CLOSE",
        "China coking coal futures continuous close",
        "CNY/tonne",
        "焦煤主连收盘价，用于观察焦煤期货市场预期。",
        524,
        "大商所",
        "焦煤期货收盘",
    ),
    (
        "CN_COKING_COAL_FUTURES_SETTLE",
        "China coking coal futures continuous settlement",
        "CNY/tonne",
        "焦煤主连结算价，用于观察焦煤期货定价。",
        525,
        "大商所",
        "焦煤期货结算",
    ),
    (
        "CN_COKE_FUTURES_CLOSE",
        "China coke futures continuous close",
        "CNY/tonne",
        "焦炭主连收盘价，用于观察焦化利润和钢厂需求预期。",
        526,
        "大商所",
        "焦炭期货收盘",
    ),
    (
        "CN_COKE_FUTURES_SETTLE",
        "China coke futures continuous settlement",
        "CNY/tonne",
        "焦炭主连结算价，用于观察焦炭期货定价。",
        527,
        "大商所",
        "焦炭期货结算",
    ),
    (
        "CN_COKING_COAL_99QH_INVENTORY",
        "China coking coal 99qh inventory",
        "tonne",
        "99 期货网焦煤库存，用于观察交易所相关库存变化。",
        528,
        "99期货",
        "焦煤库存",
    ),
    (
        "CN_COKE_99QH_INVENTORY",
        "China coke 99qh inventory",
        "tonne",
        "99 期货网焦炭库存，用于观察焦炭库存变化。",
        529,
        "99期货",
        "焦炭库存",
    ),
    (
        "CN_METHANOL_99QH_INVENTORY",
        "China methanol 99qh inventory",
        "tonne",
        "99 期货网甲醇库存，用于补充观察煤化工链条。",
        530,
        "99期货",
        "甲醇库存",
    ),
]

_COAL_AKSHARE_INDICATORS = [
    _indicator(
        code=code,
        name=name,
        domain="coal",
        region="China",
        unit=unit,
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES[code]["source"],
        description=description,
        display_order=display_order,
        selectors={"country": "China", "market": market, "metric": metric},
    )
    for code, name, unit, description, display_order, market, metric in (
        _COAL_AKSHARE_INDICATOR_SPECS
    )
]

_WORLD_BANK_INDICATORS = [
    _indicator(
        code="CN_GDP",
        name="China GDP",
        domain="country_macro",
        region="China",
        unit="USD",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['CN_GDP'][1]}",
        description="中国现价美元 GDP，用于观察中国经济总量变化。",
        display_order=111,
        selectors={"country": "China", "category": "经济总量", "metric": "GDP"},
    ),
    _indicator(
        code="JP_GDP",
        name="Japan GDP",
        domain="country_macro",
        region="Japan",
        unit="USD",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['JP_GDP'][1]}",
        description="日本现价美元 GDP，用于观察日本经济总量变化。",
        display_order=112,
        selectors={"country": "Japan", "metric": "GDP"},
    ),
    _indicator(
        code="EU_GDP",
        name="Euro Area GDP",
        domain="country_macro",
        region="Euro Area",
        unit="USD",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['EU_GDP'][1]}",
        description="欧元区现价美元 GDP，用于观察欧洲经济总量变化。",
        display_order=113,
        selectors={"country": "Euro Area", "metric": "GDP"},
    ),
    _indicator(
        code="CN_DEBT_TO_GDP",
        name="China central government debt to GDP",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['CN_DEBT_TO_GDP'][1]}",
        description="中国中央政府债务占 GDP 比重，用于观察财政杠杆。",
        display_order=121,
        selectors={"country": "China", "metric": "Debt/GDP"},
        availability=_availability_for("CN_DEBT_TO_GDP"),
    ),
    _indicator(
        code="JP_DEBT_TO_GDP",
        name="Japan central government debt to GDP",
        domain="country_macro",
        region="Japan",
        unit="%",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['JP_DEBT_TO_GDP'][1]}",
        description="日本中央政府债务占 GDP 比重，用于观察债务负担。",
        display_order=122,
        selectors={"country": "Japan", "metric": "Debt/GDP"},
    ),
    _indicator(
        code="EU_DEBT_TO_GDP",
        name="Euro Area central government debt to GDP",
        domain="country_macro",
        region="Euro Area",
        unit="%",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['EU_DEBT_TO_GDP'][1]}",
        description="欧元区中央政府债务占 GDP 比重，用于观察债务负担。",
        display_order=123,
        selectors={"country": "Euro Area", "metric": "Debt/GDP"},
    ),
    _indicator(
        code="CN_FISCAL_BALANCE_TO_GDP",
        name="China fiscal balance to GDP",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['CN_FISCAL_BALANCE_TO_GDP'][1]}",
        description="中国财政余额占 GDP 比重，负值代表财政赤字。",
        display_order=131,
        selectors={"country": "China", "metric": "Fiscal balance"},
        availability=_availability_for("CN_FISCAL_BALANCE_TO_GDP"),
    ),
    _indicator(
        code="JP_FISCAL_BALANCE_TO_GDP",
        name="Japan fiscal balance to GDP",
        domain="country_macro",
        region="Japan",
        unit="%",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['JP_FISCAL_BALANCE_TO_GDP'][1]}",
        description="日本财政余额占 GDP 比重，负值代表财政赤字。",
        display_order=132,
        selectors={"country": "Japan", "metric": "Fiscal balance"},
    ),
    _indicator(
        code="EU_FISCAL_BALANCE_TO_GDP",
        name="Euro Area fiscal balance to GDP",
        domain="country_macro",
        region="Euro Area",
        unit="%",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['EU_FISCAL_BALANCE_TO_GDP'][1]}",
        description="欧元区财政余额占 GDP 比重，负值代表财政赤字。",
        display_order=133,
        selectors={"country": "Euro Area", "metric": "Fiscal balance"},
    ),
]

_CHINA_DATA_INDICATORS = [
    _indicator(
        code="CN_M2",
        name="China M2 money supply",
        domain="country_macro",
        region="China",
        unit="100 million CNY",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_M2"]["source"],
        description="中国 M2 广义货币供应量，用于观察总量流动性。",
        display_order=142,
        selectors={"country": "China", "category": "汇率与金融", "metric": "M2"},
    ),
    _indicator(
        code="CN_M2_YOY",
        name="China M2 money supply YoY",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_M2_YOY"]["source"],
        description="中国 M2 同比增速，用于观察总量流动性扩张速度。",
        display_order=143,
        selectors={"country": "China", "category": "汇率与金融", "metric": "M2同比"},
    ),
]

_CHINA_AKSHARE_EXTRA_INDICATORS = [
    _indicator(
        code="CN_NOMINAL_GDP_QUARTERLY",
        name="China nominal GDP quarterly",
        domain="country_macro",
        region="China",
        unit="100 million CNY",
        frequency="quarterly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_NOMINAL_GDP_QUARTERLY"]["source"],
        description="中国季度现价 GDP 累计值，用于观察国内经济总量。",
        display_order=113,
        selectors={"country": "China", "category": "经济总量", "metric": "名义GDP"},
    ),
    _indicator(
        code="CN_REAL_GDP_QUARTERLY_YOY",
        name="China real GDP quarterly YoY",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="quarterly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_REAL_GDP_QUARTERLY_YOY"]["source"],
        description="中国 GDP 不变价同比增速，用于观察实际增长。",
        display_order=114,
        selectors={"country": "China", "category": "经济总量", "metric": "实际GDP"},
    ),
    _indicator(
        code="CN_EXPORT_YOY_USD",
        name="China exports YoY in USD",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_EXPORT_YOY_USD"]["source"],
        description="中国以美元计出口同比，用于观察外需变化。",
        display_order=216,
        selectors={"country": "China", "category": "价格与进出口", "metric": "出口同比"},
    ),
    _indicator(
        code="CN_EXPORT_VALUE_USD",
        name="China exports value in USD",
        domain="country_macro",
        region="China",
        unit="USD 100mn",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_EXPORT_VALUE_USD"]["source"],
        description="中国海关总署口径当月出口额，折算为亿美元，用于观察外需规模。",
        display_order=216,
        selectors={"country": "China", "category": "价格与进出口", "metric": "出口额"},
    ),
    _indicator(
        code="CN_IMPORT_YOY_USD",
        name="China imports YoY in USD",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_IMPORT_YOY_USD"]["source"],
        description="中国以美元计进口同比，用于观察内需与补库变化。",
        display_order=217,
        selectors={"country": "China", "category": "价格与进出口", "metric": "进口同比"},
    ),
    _indicator(
        code="CN_IMPORT_VALUE_USD",
        name="China imports value in USD",
        domain="country_macro",
        region="China",
        unit="USD 100mn",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_IMPORT_VALUE_USD"]["source"],
        description="中国海关总署口径当月进口额，折算为亿美元，用于观察内需和补库规模。",
        display_order=217,
        selectors={"country": "China", "category": "价格与进出口", "metric": "进口额"},
    ),
]

_CHINA_WORLD_BANK_EXTRA_INDICATORS = [
    _indicator(
        code="CN_REAL_GDP_GROWTH",
        name="China real GDP growth",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['CN_REAL_GDP_GROWTH'][1]}",
        description="中国实际 GDP 年度增速，用于观察经济总量的真实增长。",
        display_order=112,
        selectors={"country": "China", "category": "经济总量", "metric": "实际GDP增速"},
    ),
    _indicator(
        code="CN_HOUSEHOLD_CONSUMPTION",
        name="China household consumption",
        domain="country_macro",
        region="China",
        unit="USD",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['CN_HOUSEHOLD_CONSUMPTION'][1]}",
        description="中国居民最终消费支出，用于观察消费对经济的拉动。",
        display_order=150,
        selectors={"country": "China", "category": "消费", "metric": "居民消费支出"},
    ),
    _indicator(
        code="CN_GROSS_CAPITAL_FORMATION",
        name="China gross capital formation",
        domain="country_macro",
        region="China",
        unit="USD",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['CN_GROSS_CAPITAL_FORMATION'][1]}",
        description="中国资本形成总额，用于观察投资和库存变动形成的总需求。",
        display_order=170,
        selectors={"country": "China", "category": "工业与投资", "metric": "资本形成总额"},
    ),
    _indicator(
        code="CN_INDUSTRY_VALUE_ADDED",
        name="China industry value added",
        domain="country_macro",
        region="China",
        unit="USD",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['CN_INDUSTRY_VALUE_ADDED'][1]}",
        description="中国工业增加值，用于观察工业部门产出规模。",
        display_order=171,
        selectors={"country": "China", "category": "工业与投资", "metric": "工业增加值"},
    ),
    _indicator(
        code="CN_EXPORTS_GOODS_SERVICES",
        name="China exports of goods and services",
        domain="country_macro",
        region="China",
        unit="USD",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['CN_EXPORTS_GOODS_SERVICES'][1]}",
        description="中国货物和服务出口额，用于观察外需变化。",
        display_order=210,
        selectors={"country": "China", "category": "价格与进出口", "metric": "出口额"},
    ),
    _indicator(
        code="CN_IMPORTS_GOODS_SERVICES",
        name="China imports of goods and services",
        domain="country_macro",
        region="China",
        unit="USD",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['CN_IMPORTS_GOODS_SERVICES'][1]}",
        description="中国货物和服务进口额，用于观察内需和补库变化。",
        display_order=211,
        selectors={"country": "China", "category": "价格与进出口", "metric": "进口额"},
    ),
    _indicator(
        code="CN_CPI_INFLATION",
        name="China CPI inflation",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['CN_CPI_INFLATION'][1]}",
        description="中国 CPI 年度通胀率，用于观察居民端价格压力。",
        display_order=212,
        selectors={"country": "China", "category": "价格与进出口", "metric": "CPI通胀"},
    ),
    _indicator(
        code="CN_OFFICIAL_EXCHANGE_RATE",
        name="China official exchange rate",
        domain="country_macro",
        region="China",
        unit="CNY/USD",
        frequency="annual",
        provider="world_bank",
        source=f"WorldBank:{WORLD_BANK_SERIES['CN_OFFICIAL_EXCHANGE_RATE'][1]}",
        description="人民币兑美元官方平均汇率，用于观察汇率与外部金融条件。",
        display_order=232,
        selectors={"country": "China", "category": "汇率与金融", "metric": "人民币汇率"},
    ),
]

_KEY_GATED_INDICATORS = [
    _indicator(
        code="US_EIA_CRUDE_STOCKS",
        name="U.S. commercial crude oil stocks",
        domain="crude_oil",
        region="United States",
        unit="thousand barrels",
        frequency="weekly",
        provider="unavailable",
        source="Pending:EIA API",
        description="美国商业原油库存用于观察原油供需平衡和炼厂补库节奏。",
        display_order=405,
        selectors={"country": "United States", "commodity": "Crude oil", "metric": "Inventory"},
        availability=_availability_for("US_EIA_CRUDE_STOCKS"),
    ),
    _indicator(
        code="US_API_CRUDE_STOCK_CHANGE",
        name="U.S. API crude oil stock change",
        domain="crude_oil",
        region="United States",
        unit="10k barrels",
        frequency="weekly",
        provider="unavailable",
        source="Pending:API official feed",
        description="美国 API 原油库存周度变动值；当前公开事件源已停更，不进入可用监控。",
        display_order=406,
        selectors={"country": "United States", "commodity": "Crude oil", "metric": "Stock change"},
        availability=_availability_for("US_API_CRUDE_STOCK_CHANGE"),
    ),
    _indicator(
        code="US_EIA_CRUDE_STOCK_CHANGE",
        name="U.S. EIA crude oil stock change",
        domain="crude_oil",
        region="United States",
        unit="10k barrels",
        frequency="weekly",
        provider="unavailable",
        source="Pending:EIA API",
        description="美国 EIA 原油库存周度变动值；当前公开事件源已停更，不进入可用监控。",
        display_order=407,
        selectors={
            "country": "United States",
            "commodity": "Crude oil",
            "metric": "EIA stock change",
        },
        availability=_availability_for("US_EIA_CRUDE_STOCK_CHANGE"),
    ),
]

_CRUDE_OIL_AKSHARE_INDICATORS = [
    _indicator(
        code="US_CRUDE_OIL_PRODUCTION",
        name="U.S. crude oil production",
        domain="crude_oil",
        region="United States",
        unit="10k bbl/day",
        frequency="weekly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["US_CRUDE_OIL_PRODUCTION"]["source"],
        description="美国国内原油周度产量，用于观察供应端变化。",
        display_order=408,
        selectors={"country": "United States", "commodity": "Crude oil", "metric": "Production"},
    ),
    _indicator(
        code="US_CRUDE_OIL_PRODUCTION_CHANGE",
        name="U.S. crude oil production change",
        domain="crude_oil",
        region="United States",
        unit="10k bbl/day",
        frequency="weekly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["US_CRUDE_OIL_PRODUCTION_CHANGE"]["source"],
        description="美国国内原油周度产量变化，用于观察供应边际变化。",
        display_order=409,
        selectors={
            "country": "United States",
            "commodity": "Crude oil",
            "metric": "Production change",
        },
    ),
    _indicator(
        code="CN_GASOLINE_RETAIL_PRICE",
        name="China gasoline retail guide price",
        domain="crude_oil",
        region="China",
        unit="CNY/tonne",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_GASOLINE_RETAIL_PRICE"]["source"],
        description="中国汽油调价价格，用于观察国内成品油价格传导。",
        display_order=410,
        selectors={"country": "China", "commodity": "Gasoline", "metric": "Retail guide price"},
    ),
    _indicator(
        code="CN_DIESEL_RETAIL_PRICE",
        name="China diesel retail guide price",
        domain="crude_oil",
        region="China",
        unit="CNY/tonne",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_DIESEL_RETAIL_PRICE"]["source"],
        description="中国柴油调价价格，用于观察国内成品油价格传导。",
        display_order=411,
        selectors={"country": "China", "commodity": "Diesel", "metric": "Retail guide price"},
    ),
]

_OIL_SHIPPING_INDICATORS = [
    _indicator(
        code="BDTI_INDEX",
        name="Baltic Dirty Tanker Index",
        domain="oil_shipping",
        region="Global",
        unit="index",
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["BDTI_INDEX"]["source"],
        description="BDTI 原油运输指数，用于观察脏油轮运价。",
        display_order=701,
        selectors={"market": "Baltic Exchange", "segment": "Dirty tanker", "metric": "BDTI"},
    ),
    _indicator(
        code="BCTI_INDEX",
        name="Baltic Clean Tanker Index",
        domain="oil_shipping",
        region="Global",
        unit="index",
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["BCTI_INDEX"]["source"],
        description="BCTI 成品油运输指数，用于观察成品油轮运价。",
        display_order=702,
        selectors={"market": "Baltic Exchange", "segment": "Clean tanker", "metric": "BCTI"},
    ),
    _indicator(
        code="BDI_INDEX",
        name="Baltic Dry Index",
        domain="oil_shipping",
        region="Global",
        unit="index",
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["BDI_INDEX"]["source"],
        description="BDI 波罗的海干散货指数，用于横向比较海运景气。",
        display_order=703,
        selectors={"market": "Baltic Exchange", "segment": "Dry bulk", "metric": "BDI"},
    ),
    _indicator(
        code="BCI_INDEX",
        name="Baltic Capesize Index",
        domain="oil_shipping",
        region="Global",
        unit="index",
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["BCI_INDEX"]["source"],
        description="BCI 好望角型船指数，用于观察大船运价景气。",
        display_order=704,
        selectors={"market": "Baltic Exchange", "segment": "Capesize", "metric": "BCI"},
    ),
    _indicator(
        code="BPI_INDEX",
        name="Baltic Panamax Index",
        domain="oil_shipping",
        region="Global",
        unit="index",
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["BPI_INDEX"]["source"],
        description="BPI 巴拿马型船指数，用于观察中型散货船运价景气。",
        display_order=705,
        selectors={"market": "Baltic Exchange", "segment": "Panamax", "metric": "BPI"},
    ),
]

_ROUTE_TANKER_SPECS = [
    ("TD3C", "Dirty tanker", "Middle East Gulf to China VLCC"),
    ("TD7", "Dirty tanker", "North Sea to Continent Aframax"),
    ("TD8", "Dirty tanker", "Kuwait to Singapore Aframax"),
    ("TD9", "Dirty tanker", "Caribbean to U.S. Gulf Aframax"),
    ("TD14", "Dirty tanker", "Southeast Asia to east coast Australia Aframax"),
    ("TD15", "Dirty tanker", "West Africa to China Suezmax"),
    ("TD19", "Dirty tanker", "cross-Mediterranean Aframax"),
    ("TD20", "Dirty tanker", "West Africa to Europe Suezmax"),
    ("TD22", "Dirty tanker", "U.S. Gulf to China VLCC"),
    ("TD25", "Dirty tanker", "U.S. Gulf to Europe Aframax"),
    ("TC2", "Clean tanker", "Continent to U.S. Atlantic Coast MR"),
    ("TC5", "Clean tanker", "Middle East Gulf to Japan LR2"),
    ("TC6", "Clean tanker", "Algeria to European Mediterranean MR"),
    ("TC8", "Clean tanker", "Middle East Gulf to U.K. Continent LR1"),
    ("TC14", "Clean tanker", "U.S. Gulf to Continent MR"),
    ("TC17", "Clean tanker", "Middle East Gulf to East Africa MR"),
    ("TC20", "Clean tanker", "Middle East Gulf to U.K. Continent LR2"),
]

_ROUTE_TANKER_PENDING_INDICATORS = [
    _indicator(
        code=f"{route}_TANKER_FREIGHT",
        name=f"{route} {description} tanker freight",
        domain="oil_shipping",
        region="Global",
        unit="Worldscale / USD per tonne",
        frequency="daily",
        provider="unavailable",
        source="Pending:Baltic Exchange route data",
        description=f"{route} {description} 航线运价，用于观察航线级油运成本。",
        display_order=706 + index,
        selectors={"market": "Baltic Exchange", "segment": segment, "route": route},
        availability=_availability_for(f"{route}_TANKER_FREIGHT"),
    )
    for index, (route, segment, description) in enumerate(_ROUTE_TANKER_SPECS)
]

_EIA_PUBLIC_INDICATOR_SPECS = [
    (
        "EIA_US_CRUDE_STOCKS_EX_SPR",
        "EIA U.S. crude stocks excluding SPR",
        "thousand barrels",
        "美国商业原油库存（不含 SPR），用于观察商业库存和供需平衡。",
        412,
        "Inventory",
    ),
    (
        "EIA_US_TOTAL_CRUDE_STOCKS",
        "EIA U.S. total crude stocks",
        "thousand barrels",
        "美国原油总库存（含 SPR），用于观察原油总体库存水位。",
        413,
        "Inventory",
    ),
    (
        "EIA_CUSHING_CRUDE_STOCKS",
        "EIA Cushing crude stocks",
        "thousand barrels",
        "库欣原油库存，用于观察 WTI 交割地库存压力。",
        414,
        "Cushing inventory",
    ),
    (
        "EIA_US_SPR_CRUDE_STOCKS",
        "EIA U.S. SPR crude stocks",
        "thousand barrels",
        "美国战略石油储备库存，用于观察政策储备变化。",
        415,
        "SPR inventory",
    ),
    (
        "EIA_US_CRUDE_PRODUCTION",
        "EIA U.S. crude oil production",
        "thousand barrels/day",
        "EIA 美国原油周度产量，用于观察供应端变化。",
        416,
        "Production",
    ),
    (
        "EIA_LOWER48_CRUDE_PRODUCTION",
        "EIA Lower 48 crude oil production",
        "thousand barrels/day",
        "EIA 美国本土 48 州原油周度产量，用于剔除阿拉斯加后的供应观察。",
        417,
        "Lower 48 production",
    ),
    (
        "EIA_US_CRUDE_IMPORTS",
        "EIA U.S. crude oil imports",
        "thousand barrels/day",
        "美国原油进口量，用于观察外部供给和炼厂采购。",
        418,
        "Imports",
    ),
    (
        "EIA_US_CRUDE_EXPORTS",
        "EIA U.S. crude oil exports",
        "thousand barrels/day",
        "美国原油出口量，用于观察出口套利和全球流向。",
        419,
        "Exports",
    ),
    (
        "EIA_US_REFINERY_CRUDE_INPUTS",
        "EIA U.S. refinery crude inputs",
        "thousand barrels/day",
        "美国炼厂原油净投入，用于观察炼厂需求。",
        420,
        "Refinery input",
    ),
    (
        "EIA_US_REFINERY_UTILIZATION",
        "EIA U.S. refinery utilization",
        "%",
        "美国炼厂开工率，用于观察炼化负荷。",
        421,
        "Refinery utilization",
    ),
    (
        "EIA_US_TOTAL_GASOLINE_STOCKS",
        "EIA U.S. total gasoline stocks",
        "thousand barrels",
        "美国汽油库存，用于观察成品油供需。",
        422,
        "Gasoline stocks",
    ),
    (
        "EIA_US_DISTILLATE_STOCKS",
        "EIA U.S. distillate stocks",
        "thousand barrels",
        "美国馏分油库存，用于观察柴油和取暖油供需。",
        423,
        "Distillate stocks",
    ),
    (
        "EIA_US_JET_FUEL_STOCKS",
        "EIA U.S. jet fuel stocks",
        "thousand barrels",
        "美国航煤库存，用于观察航空燃料供需。",
        424,
        "Jet fuel stocks",
    ),
    (
        "EIA_US_TOTAL_PETROLEUM_STOCKS",
        "EIA U.S. total petroleum stocks",
        "thousand barrels",
        "美国原油及石油产品总库存，用于观察全油品库存水位。",
        425,
        "Total petroleum stocks",
    ),
]

_EIA_PUBLIC_INDICATORS = [
    _indicator(
        code=code,
        name=name,
        domain="crude_oil",
        region="United States",
        unit=unit,
        frequency="weekly",
        provider="eia_public",
        source=EIA_PUBLIC_SERIES[code]["source"],
        description=description,
        display_order=display_order,
        selectors={"country": "United States", "source": "EIA", "metric": metric},
    )
    for code, name, unit, description, display_order, metric in _EIA_PUBLIC_INDICATOR_SPECS
]

_EXCHANGE_PENDING_INDICATORS = [
    _indicator(
        code="LME_COPPER_INVENTORY",
        name="LME copper inventory",
        domain="nonferrous",
        region="Global",
        unit="tonne",
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["LME_COPPER_INVENTORY"]["source"],
        description="LME 铜库存用于观察海外有色金属显性库存变化。",
        display_order=307,
        selectors={"commodity": "Copper", "market": "LME", "metric": "Inventory"},
    ),
    _indicator(
        code="LME_ALUMINUM_INVENTORY",
        name="LME aluminum inventory",
        domain="nonferrous",
        region="Global",
        unit="tonne",
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["LME_ALUMINUM_INVENTORY"]["source"],
        description="LME 铝库存用于观察海外轻金属显性库存变化。",
        display_order=308,
        selectors={"commodity": "Aluminum", "market": "LME", "metric": "Inventory"},
    ),
    _indicator(
        code="LME_ZINC_INVENTORY",
        name="LME zinc inventory",
        domain="nonferrous",
        region="Global",
        unit="tonne",
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["LME_ZINC_INVENTORY"]["source"],
        description="LME 锌库存用于观察海外镀锌和基建需求相关库存变化。",
        display_order=309,
        selectors={"commodity": "Zinc", "market": "LME", "metric": "Inventory"},
    ),
    _indicator(
        code="LME_NICKEL_INVENTORY",
        name="LME nickel inventory",
        domain="nonferrous",
        region="Global",
        unit="tonne",
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["LME_NICKEL_INVENTORY"]["source"],
        description="LME 镍库存用于观察不锈钢和新能源材料链库存变化。",
        display_order=310,
        selectors={"commodity": "Nickel", "market": "LME", "metric": "Inventory"},
    ),
    _indicator(
        code="COMEX_GOLD_INVENTORY",
        name="COMEX gold inventory",
        domain="nonferrous",
        region="Global",
        unit="tonne",
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["COMEX_GOLD_INVENTORY"]["source"],
        description="COMEX 黄金库存用于补充观察贵金属市场显性库存。",
        display_order=311,
        selectors={"commodity": "Gold", "market": "COMEX", "metric": "Inventory"},
    ),
    _indicator(
        code="SHFE_COPPER_INVENTORY",
        name="SHFE copper inventory",
        domain="nonferrous",
        region="China",
        unit="tonne",
        frequency="weekly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["SHFE_COPPER_INVENTORY"]["source"],
        description="上期所铜库存用于观察国内有色金属显性库存变化。",
        display_order=308,
        selectors={"commodity": "Copper", "market": "SHFE", "metric": "Inventory"},
    ),
]

_NONFERROUS_AKSHARE_SPECS = [
    (
        "CN_PBOC_GOLD_RESERVE",
        "PBOC gold reserve",
        "10k troy oz",
        "中国央行黄金储备用于观察官方部门黄金配置变化。",
        312,
        "Gold",
        "PBOC",
        "Official reserve",
    ),
    (
        "CN_PBOC_FX_RESERVE",
        "China foreign exchange reserve",
        "USD 100mn",
        "中国外汇储备用于配合观察官方储备资产变化。",
        313,
        "Gold",
        "PBOC",
        "FX reserve",
    ),
    (
        "CN_GOLD_ETF_HOLDINGS",
        "Gold ETF holdings",
        "tonne",
        "黄金 ETF 总库存用于观察投资需求和显性持仓变化。",
        314,
        "Gold",
        "ETF",
        "Holdings",
    ),
    (
        "CN_GOLD_ETF_HOLDINGS_CHANGE",
        "Gold ETF holdings change",
        "tonne",
        "黄金 ETF 增持/减持用于观察投资需求边际变化。",
        315,
        "Gold",
        "ETF",
        "Holdings change",
    ),
    (
        "SGE_AU9999_CLOSE",
        "SGE Au99.99 close",
        "CNY/g",
        "上海黄金交易所 Au99.99 收盘价用于观察国内现货黄金定价。",
        316,
        "Gold",
        "SGE",
        "Spot close",
    ),
    (
        "SGE_GOLD_BENCHMARK_PM",
        "Shanghai gold benchmark PM",
        "CNY/g",
        "上海金基准晚盘价用于观察人民币黄金基准价格。",
        317,
        "Gold",
        "SGE",
        "Benchmark PM",
    ),
    (
        "SHFE_GOLD_FUTURES_CLOSE",
        "SHFE gold futures continuous close",
        "CNY/g",
        "沪金主连收盘价用于观察国内黄金期货定价。",
        318,
        "Gold",
        "SHFE",
        "Futures close",
    ),
    (
        "SHFE_GOLD_FUTURES_SETTLE",
        "SHFE gold futures continuous settlement",
        "CNY/g",
        "沪金主连结算价用于观察国内黄金期货结算定价。",
        319,
        "Gold",
        "SHFE",
        "Futures settlement",
    ),
    (
        "SHFE_SILVER_FUTURES_CLOSE",
        "SHFE silver futures continuous close",
        "CNY/kg",
        "沪银主连收盘价用于观察贵金属链条风险偏好。",
        320,
        "Silver",
        "SHFE",
        "Futures close",
    ),
    (
        "SHFE_COPPER_FUTURES_CLOSE",
        "SHFE copper futures continuous close",
        "CNY/tonne",
        "沪铜主连收盘价，用于观察国内铜期货定价。",
        321,
        "Copper",
        "SHFE",
        "Futures close",
    ),
    (
        "SHFE_COPPER_FUTURES_SETTLE",
        "SHFE copper futures continuous settlement",
        "CNY/tonne",
        "沪铜主连结算价，用于观察国内铜期货结算定价。",
        322,
        "Copper",
        "SHFE",
        "Futures settlement",
    ),
    (
        "SHFE_ALUMINUM_FUTURES_CLOSE",
        "SHFE aluminum futures continuous close",
        "CNY/tonne",
        "沪铝主连收盘价，用于观察国内铝期货定价。",
        323,
        "Aluminum",
        "SHFE",
        "Futures close",
    ),
    (
        "SHFE_ZINC_FUTURES_CLOSE",
        "SHFE zinc futures continuous close",
        "CNY/tonne",
        "沪锌主连收盘价，用于观察国内锌期货定价。",
        324,
        "Zinc",
        "SHFE",
        "Futures close",
    ),
    (
        "SHFE_LEAD_FUTURES_CLOSE",
        "SHFE lead futures continuous close",
        "CNY/tonne",
        "沪铅主连收盘价，用于观察国内铅期货定价。",
        325,
        "Lead",
        "SHFE",
        "Futures close",
    ),
    (
        "SHFE_NICKEL_FUTURES_CLOSE",
        "SHFE nickel futures continuous close",
        "CNY/tonne",
        "沪镍主连收盘价，用于观察国内镍期货定价。",
        326,
        "Nickel",
        "SHFE",
        "Futures close",
    ),
    (
        "SHFE_TIN_FUTURES_CLOSE",
        "SHFE tin futures continuous close",
        "CNY/tonne",
        "沪锡主连收盘价，用于观察国内锡期货定价。",
        327,
        "Tin",
        "SHFE",
        "Futures close",
    ),
    (
        "SHFE_ALUMINA_FUTURES_CLOSE",
        "SHFE alumina futures continuous close",
        "CNY/tonne",
        "氧化铝主连收盘价，用于观察铝产业链中间品价格。",
        328,
        "Alumina",
        "SHFE",
        "Futures close",
    ),
    (
        "GFEX_INDUSTRIAL_SILICON_FUTURES_CLOSE",
        "GFEX industrial silicon futures continuous close",
        "CNY/tonne",
        "工业硅主连收盘价，用于观察硅铝及新能源材料链。",
        329,
        "Industrial silicon",
        "GFEX",
        "Futures close",
    ),
    (
        "INE_BONDED_COPPER_FUTURES_CLOSE",
        "INE bonded copper futures continuous close",
        "CNY/tonne",
        "国际铜主连收盘价，用于观察保税铜定价。",
        330,
        "Copper",
        "INE",
        "Futures close",
    ),
    (
        "SHFE_COPPER_INVENTORY_DAILY",
        "SHFE copper inventory daily",
        "tonne",
        "东方财富口径沪铜日频库存，用于提高 SHFE 铜库存当前性。",
        331,
        "Copper",
        "SHFE",
        "Daily inventory",
    ),
    (
        "SHFE_COPPER_99QH_INVENTORY",
        "SHFE copper 99qh inventory",
        "tonne",
        "99 期货网上期所铜库存，用于补充周频交易所库存历史。",
        332,
        "Copper",
        "SHFE",
        "99qh inventory",
    ),
    (
        "SHFE_ALUMINUM_99QH_INVENTORY",
        "SHFE aluminum 99qh inventory",
        "tonne",
        "99 期货网上期所铝库存，用于补充周频交易所库存历史。",
        333,
        "Aluminum",
        "SHFE",
        "99qh inventory",
    ),
    (
        "SHFE_ZINC_99QH_INVENTORY",
        "SHFE zinc 99qh inventory",
        "tonne",
        "99 期货网上期所锌库存，用于补充周频交易所库存历史。",
        334,
        "Zinc",
        "SHFE",
        "99qh inventory",
    ),
    (
        "SHFE_NICKEL_99QH_INVENTORY",
        "SHFE nickel 99qh inventory",
        "tonne",
        "99 期货网上期所镍库存，用于补充周频交易所库存历史。",
        335,
        "Nickel",
        "SHFE",
        "99qh inventory",
    ),
    (
        "SHFE_LEAD_99QH_INVENTORY",
        "SHFE lead 99qh inventory",
        "tonne",
        "99 期货网上期所铅库存，用于补充周频交易所库存历史。",
        336,
        "Lead",
        "SHFE",
        "99qh inventory",
    ),
    (
        "CN_COMMODITY_PRICE_INDEX",
        "China commodity price index",
        "index",
        "中国大宗商品价格指数，用于观察工业品和有色链条整体价格环境。",
        337,
        "Industrial commodities",
        "China",
        "Commodity index",
    ),
]

_NONFERROUS_AKSHARE_INDICATORS = [
    _indicator(
        code=code,
        name=name,
        domain="nonferrous",
        region="China",
        unit=unit,
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES[code]["source"],
        description=description,
        display_order=display_order,
        selectors={"commodity": commodity, "metric": f"{market} {metric}"},
    )
    for code, name, unit, description, display_order, commodity, market, metric in (
        _NONFERROUS_AKSHARE_SPECS
    )
]

_POWER_AKSHARE_INDICATORS = [
    _indicator(
        code="CN_SOCIETY_ELECTRICITY",
        name="China total electricity consumption",
        domain="power",
        region="China",
        unit="100 million kWh",
        frequency="monthly",
        provider="nea_public",
        source="国家能源局:全社会用电量",
        description="中国全社会用电量用于观察实体经济活动和电力需求。",
        display_order=602,
        selectors={"country": "China", "metric": "Electricity consumption"},
    ),
    _indicator(
        code="CN_SOCIETY_ELECTRICITY_YOY",
        name="China total electricity consumption YoY",
        domain="power",
        region="China",
        unit="%",
        frequency="monthly",
        provider="nea_public",
        source="国家能源局:全社会用电量",
        description="中国全社会用电量同比用于观察实体经济用电强弱。",
        display_order=603,
        selectors={"country": "China", "metric": "Electricity consumption YoY"},
    ),
    _indicator(
        code="CN_ENERGY_INDEX",
        name="China energy index",
        domain="power",
        region="China",
        unit="index",
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_ENERGY_INDEX"]["source"],
        description="中国能源指数用于观察能源板块景气和风险偏好。",
        display_order=604,
        selectors={"country": "China", "metric": "Energy index"},
    ),
]

_POWER_AKSHARE_EXTRA_SPECS = [
    (
        "CN_PRIMARY_INDUSTRY_ELECTRICITY",
        "China primary industry electricity consumption",
        "100 million kWh",
        "第一产业用电量，用于观察农业和乡村生产用电需求。",
        605,
        "Primary electricity",
    ),
    (
        "CN_PRIMARY_INDUSTRY_ELECTRICITY_YOY",
        "China primary industry electricity consumption YoY",
        "%",
        "第一产业用电量同比，用于观察农业和乡村生产用电增速。",
        606,
        "Primary electricity YoY",
    ),
    (
        "CN_SECONDARY_INDUSTRY_ELECTRICITY",
        "China secondary industry electricity consumption",
        "100 million kWh",
        "第二产业用电量，用于观察工业生产和制造业景气。",
        607,
        "Secondary electricity",
    ),
    (
        "CN_SECONDARY_INDUSTRY_ELECTRICITY_YOY",
        "China secondary industry electricity consumption YoY",
        "%",
        "第二产业用电量同比，用于观察工业用电强弱。",
        608,
        "Secondary electricity YoY",
    ),
    (
        "CN_TERTIARY_INDUSTRY_ELECTRICITY",
        "China tertiary industry electricity consumption",
        "100 million kWh",
        "第三产业用电量，用于观察服务业活动。",
        609,
        "Tertiary electricity",
    ),
    (
        "CN_TERTIARY_INDUSTRY_ELECTRICITY_YOY",
        "China tertiary industry electricity consumption YoY",
        "%",
        "第三产业用电量同比，用于观察服务业用电增速。",
        610,
        "Tertiary electricity YoY",
    ),
    (
        "CN_RESIDENTIAL_ELECTRICITY",
        "China residential electricity consumption",
        "100 million kWh",
        "城乡居民生活用电量，用于观察居民端电力需求。",
        611,
        "Residential electricity",
    ),
    (
        "CN_RESIDENTIAL_ELECTRICITY_YOY",
        "China residential electricity consumption YoY",
        "%",
        "城乡居民生活用电量同比，用于观察居民端用电增速。",
        612,
        "Residential electricity YoY",
    ),
    (
        "CN_BEIJING_CARBON_AVG_PRICE",
        "Beijing carbon allowance average price",
        "CNY/tonne",
        "北京碳排放权成交均价，用于观察绿电与碳成本环境。",
        613,
        "Beijing carbon",
    ),
    (
        "CN_HUBEI_CARBON_PRICE",
        "Hubei carbon allowance trade price",
        "CNY/tonne",
        "湖北碳排放权成交价，用于观察区域碳价和绿电成本环境。",
        614,
        "Hubei carbon",
    ),
]

_POWER_AKSHARE_EXTRA_INDICATORS = [
    _indicator(
        code=code,
        name=name,
        domain="power",
        region="China",
        unit=unit,
        frequency="daily" if "CARBON" in code else "monthly",
        provider="nea_public" if code in NEA_PUBLIC_SERIES else "akshare_china",
        source=(
            "国家能源局:全社会用电量"
            if code in NEA_PUBLIC_SERIES
            else AKSHARE_CHINA_SERIES[code]["source"]
        ),
        description=description,
        display_order=display_order,
        selectors={"country": "China", "metric": metric},
    )
    for code, name, unit, description, display_order, metric in _POWER_AKSHARE_EXTRA_SPECS
]

_POWER_UNAVAILABLE_SPECS = [
    ("CN_THERMAL_POWER_GENERATION", "China thermal power generation", "火电发电量"),
    ("CN_HYDRO_POWER_GENERATION", "China hydro power generation", "水电发电量"),
    ("CN_WIND_POWER_GENERATION", "China wind power generation", "风电发电量"),
    ("CN_SOLAR_POWER_GENERATION", "China solar power generation", "太阳能发电量"),
    ("CN_NUCLEAR_POWER_GENERATION", "China nuclear power generation", "核电发电量"),
]

_POWER_UNAVAILABLE_INDICATORS = [
    _indicator(
        code=code,
        name=name,
        domain="power",
        region="China",
        unit="100 million kWh",
        frequency="monthly",
        provider="askci_public",
        source=f"中商产业研究院/NBS:{ASKCI_PUBLIC_SERIES[code]['indicator']}",
        description=f"{metric}用于观察中国电源结构变化。",
        display_order=615 + index,
        selectors={"country": "China", "metric": metric},
    )
    for index, (code, name, metric) in enumerate(_POWER_UNAVAILABLE_SPECS)
]

_ADDITIONAL_MACRO_AKSHARE_INDICATORS = [
    _indicator(
        code="CN_MANUFACTURING_PMI",
        name="China manufacturing PMI",
        domain="country_macro",
        region="China",
        unit="index",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_MANUFACTURING_PMI"]["source"],
        description="中国制造业 PMI 用于观察制造业景气和订单变化。",
        display_order=176,
        selectors={"country": "China", "category": "工业与投资", "metric": "制造业PMI"},
    ),
    _indicator(
        code="CN_NON_MANUFACTURING_PMI",
        name="China non-manufacturing PMI",
        domain="country_macro",
        region="China",
        unit="index",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_NON_MANUFACTURING_PMI"]["source"],
        description="中国非制造业 PMI 用于观察服务业和建筑业景气。",
        display_order=177,
        selectors={"country": "China", "category": "工业与投资", "metric": "非制造业PMI"},
    ),
    _indicator(
        code="CN_CORPORATE_GOODS_PRICE_INDEX",
        name="China corporate goods price index",
        domain="country_macro",
        region="China",
        unit="index",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_CORPORATE_GOODS_PRICE_INDEX"]["source"],
        description="中国企业商品价格指数用于观察上游和企业端价格压力。",
        display_order=214,
        selectors={"country": "China", "category": "价格与进出口", "metric": "企业商品价格"},
    ),
    _indicator(
        code="US_ISM_MANUFACTURING_PMI",
        name="U.S. ISM manufacturing PMI",
        domain="country_macro",
        region="United States",
        unit="index",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["US_ISM_MANUFACTURING_PMI"]["source"],
        description="美国 ISM 制造业 PMI 用于观察美国制造业景气。",
        display_order=178,
        selectors={"country": "United States", "category": "工业与投资", "metric": "ISM PMI"},
    ),
    _indicator(
        code="US_UNEMPLOYMENT_RATE",
        name="U.S. unemployment rate",
        domain="country_macro",
        region="United States",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["US_UNEMPLOYMENT_RATE"]["source"],
        description="美国失业率用于观察劳动力市场松紧。",
        display_order=179,
        selectors={"country": "United States", "category": "就业与消费", "metric": "失业率"},
    ),
    _indicator(
        code="US_NONFARM_PAYROLLS",
        name="U.S. nonfarm payrolls change",
        domain="country_macro",
        region="United States",
        unit="10k persons",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["US_NONFARM_PAYROLLS"]["source"],
        description="美国非农就业人数变动用于观察劳动力市场新增就业。",
        display_order=180,
        selectors={"country": "United States", "category": "就业与消费", "metric": "非农就业"},
    ),
    _indicator(
        code="US_CPI_YOY",
        name="U.S. CPI YoY",
        domain="country_macro",
        region="United States",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["US_CPI_YOY"]["source"],
        description="美国 CPI 同比用于观察居民端通胀压力。",
        display_order=181,
        selectors={"country": "United States", "category": "价格与进出口", "metric": "CPI同比"},
    ),
    _indicator(
        code="US_CORE_PCE_YOY",
        name="U.S. core PCE YoY",
        domain="country_macro",
        region="United States",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["US_CORE_PCE_YOY"]["source"],
        description="美国核心 PCE 年率用于观察美联储关注的通胀压力。",
        display_order=182,
        selectors={"country": "United States", "category": "价格与进出口", "metric": "核心PCE"},
    ),
    _indicator(
        code="US_RETAIL_SALES_MOM",
        name="U.S. retail sales MoM",
        domain="country_macro",
        region="United States",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["US_RETAIL_SALES_MOM"]["source"],
        description="美国零售销售月率用于观察消费需求动能。",
        display_order=183,
        selectors={"country": "United States", "category": "就业与消费", "metric": "零售销售"},
    ),
]

_UNAVAILABLE_INDICATORS = [
    _indicator(
        code="CN_REAL_GDP",
        name="China real GDP",
        domain="country_macro",
        region="China",
        unit="index / CNY",
        frequency="quarterly",
        provider="unavailable",
        source="Pending:NBS/Wind",
        description="中国实际 GDP 需要国家统计局不变价序列或 Wind 宏观数据，尚未写入模拟值。",
        display_order=110,
        selectors={"country": "China", "category": "经济总量", "metric": "Real GDP"},
        availability=_availability_for("CN_REAL_GDP"),
    ),
    _indicator(
        code="CN_TOTAL_SOCIAL_FINANCING",
        name="China total social financing",
        domain="country_macro",
        region="China",
        unit="100 million CNY",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_TOTAL_SOCIAL_FINANCING"]["source"],
        description="社会融资规模月度值用于观察实体经济融资需求。",
        display_order=140,
        selectors={"country": "China", "category": "汇率与金融", "metric": "Social financing"},
    ),
    _indicator(
        code="CN_RMB_LOANS",
        name="China RMB loans",
        domain="country_macro",
        region="China",
        unit="100 million CNY",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_RMB_LOANS"]["source"],
        description="中国新增信贷当月值，用于观察银行体系信用投放强弱。",
        display_order=141,
        selectors={"country": "China", "category": "汇率与金融", "metric": "人民币贷款"},
    ),
    _indicator(
        code="CN_M1",
        name="China M1 money supply",
        domain="country_macro",
        region="China",
        unit="100 million CNY",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_M1"]["source"],
        description="中国 M1 狭义货币供应量，用于观察企业活期资金和交易活跃度。",
        display_order=143,
        selectors={"country": "China", "category": "汇率与金融", "metric": "M1"},
    ),
    _indicator(
        code="CN_M1_YOY",
        name="China M1 money supply YoY",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_M1_YOY"]["source"],
        description="中国 M1 同比增速，用于观察企业活期资金增速。",
        display_order=145,
        selectors={"country": "China", "category": "汇率与金融", "metric": "M1同比"},
    ),
    _indicator(
        code="CN_M0",
        name="China M0 money supply",
        domain="country_macro",
        region="China",
        unit="100 million CNY",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_M0"]["source"],
        description="流通中现金 M0 用于观察居民和企业现金需求。",
        display_order=146,
        selectors={"country": "China", "category": "汇率与金融", "metric": "M0"},
    ),
    _indicator(
        code="CN_M0_YOY",
        name="China M0 money supply YoY",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_M0_YOY"]["source"],
        description="流通中现金 M0 同比增速，用于观察现金需求变化。",
        display_order=147,
        selectors={"country": "China", "category": "汇率与金融", "metric": "M0同比"},
    ),
    _indicator(
        code="CN_M1_M2_SCISSORS",
        name="China M1-M2 scissors",
        domain="country_macro",
        region="China",
        unit="percentage points",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_M1_M2_SCISSORS"]["source"],
        description="M1 同比减 M2 同比，用于观察资金活化程度。",
        display_order=148,
        selectors={"country": "China", "category": "汇率与金融", "metric": "M1-M2剪刀差"},
    ),
]

_COAL_UNAVAILABLE_INDICATORS = [
    _indicator(
        code="CN_XIAOBAODANG_MIXED_COAL_5500",
        name="Xiaobaodang 5500 kcal mixed coal price",
        domain="coal",
        region="China",
        unit="CNY/tonne",
        frequency="weekly",
        provider="unavailable",
        source="Pending:CCTD/Wind",
        description="小保当 5500 大卡混煤价格用于观察陕北矿口动力煤价格。",
        display_order=522,
        selectors={"country": "China", "market": "矿口", "metric": "小保当5500混煤"},
        availability=_availability_for("CN_XIAOBAODANG_MIXED_COAL_5500"),
    ),
    _indicator(
        code="CN_HONGLIULIN_WASHED_MIDDLE_LUMP",
        name="Hongliulin washed middle lump coal price",
        domain="coal",
        region="China",
        unit="CNY/tonne",
        frequency="weekly",
        provider="unavailable",
        source="Pending:CCTD/Wind",
        description="红柳林洗中块价格用于观察陕北块煤和化工煤需求。",
        display_order=523,
        selectors={"country": "China", "market": "矿口", "metric": "红柳林洗中块"},
        availability=_availability_for("CN_HONGLIULIN_WASHED_MIDDLE_LUMP"),
    ),
    _indicator(
        code="CN_THERMAL_COAL_FUTURES_CLOSE",
        name="China thermal coal futures continuous close",
        domain="coal",
        region="China",
        unit="CNY/tonne",
        frequency="daily",
        provider="unavailable",
        source="Pending:CZCE/Wind",
        description="动力煤主连收盘价公开行情已停更，不能作为当前监控源。",
        display_order=531,
        selectors={"country": "China", "market": "郑商所", "metric": "动力煤期货"},
        availability=_availability_for("CN_THERMAL_COAL_FUTURES_CLOSE"),
    ),
]

_CHINA_DOMESTIC_UNAVAILABLE_INDICATORS = [
    _indicator(
        code="CN_RETAIL_SALES",
        name="China retail sales",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_RETAIL_SALES"]["source"],
        description="社会消费品零售总额同比，是观察国内消费修复的核心月度指标。",
        display_order=151,
        selectors={"country": "China", "category": "消费", "metric": "社零"},
    ),
    _indicator(
        code="CN_INDUSTRIAL_PRODUCTION_YOY",
        name="China industrial production YoY",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_INDUSTRIAL_PRODUCTION_YOY"]["source"],
        description="规模以上工业增加值同比用于跟踪工业生产景气。",
        display_order=172,
        selectors={"country": "China", "category": "工业与投资", "metric": "工增同比"},
    ),
    _indicator(
        code="CN_FIXED_ASSET_INVESTMENT",
        name="China fixed asset investment",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_FIXED_ASSET_INVESTMENT"]["source"],
        description="固定资产投资累计同比用于观察投资需求。",
        display_order=173,
        selectors={"country": "China", "category": "工业与投资", "metric": "固投"},
    ),
    _indicator(
        code="CN_MANUFACTURING_INVESTMENT",
        name="China manufacturing investment",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="unavailable",
        source="Pending:NBS/Wind",
        description="制造业投资累计同比用于观察企业扩产和设备更新。",
        display_order=174,
        selectors={"country": "China", "category": "工业与投资", "metric": "制造业投资"},
        availability=_availability_for("CN_MANUFACTURING_INVESTMENT"),
    ),
    _indicator(
        code="CN_INFRASTRUCTURE_INVESTMENT",
        name="China infrastructure investment",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="unavailable",
        source="Pending:NBS/Wind",
        description="基建投资累计同比用于观察财政发力强度。",
        display_order=175,
        selectors={"country": "China", "category": "工业与投资", "metric": "基建投资"},
        availability=_availability_for("CN_INFRASTRUCTURE_INVESTMENT"),
    ),
    _indicator(
        code="CN_REAL_ESTATE_INVESTMENT",
        name="China real estate development investment",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="unavailable",
        source="Pending:NBS/Wind",
        description="房地产开发投资累计同比用于观察地产链投资强弱。",
        display_order=190,
        selectors={"country": "China", "category": "房地产", "metric": "开发投资"},
        availability=_availability_for("CN_REAL_ESTATE_INVESTMENT"),
    ),
    _indicator(
        code="CN_PROPERTY_SALES_AREA",
        name="China property sales area",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="unavailable",
        source="Pending:NBS/Wind",
        description="商品房销售面积累计同比用于观察地产销售和去化。",
        display_order=191,
        selectors={"country": "China", "category": "房地产", "metric": "销售面积"},
        availability=_availability_for("CN_PROPERTY_SALES_AREA"),
    ),
    _indicator(
        code="CN_NEW_HOME_PRICE_INDEX",
        name="China new home price index",
        domain="country_macro",
        region="China",
        unit="index",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_NEW_HOME_PRICE_INDEX"]["source"],
        description="新建商品住宅价格指数样本均值，用于观察房价变化。",
        display_order=192,
        selectors={"country": "China", "category": "房地产", "metric": "新房价格"},
    ),
    _indicator(
        code="CN_PPI",
        name="China PPI YoY",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_PPI"]["source"],
        description="中国 PPI 同比用于观察工业品出厂价格和企业盈利压力。",
        display_order=213,
        selectors={"country": "China", "category": "价格与进出口", "metric": "PPI同比"},
    ),
    _indicator(
        code="CN_PPI_INDEX",
        name="China PPI index",
        domain="country_macro",
        region="China",
        unit="index",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_PPI_INDEX"]["source"],
        description="中国 PPI 当月指数用于补充同比之外的工业品价格水平观察。",
        display_order=213,
        selectors={"country": "China", "category": "价格与进出口", "metric": "PPI当月"},
    ),
    _indicator(
        code="CN_PPI_ACCUMULATED_INDEX",
        name="China PPI accumulated index",
        domain="country_macro",
        region="China",
        unit="index",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_PPI_ACCUMULATED_INDEX"]["source"],
        description="中国 PPI 累计指数用于观察年内工业品价格累计变化。",
        display_order=213,
        selectors={"country": "China", "category": "价格与进出口", "metric": "PPI累计"},
    ),
    _indicator(
        code="CN_CPI_MONTHLY_YOY",
        name="China CPI YoY",
        domain="country_macro",
        region="China",
        unit="%",
        frequency="monthly",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_CPI_MONTHLY_YOY"]["source"],
        description="国家统计口径 CPI 月度同比，用于观察居民端通胀压力。",
        display_order=214,
        selectors={"country": "China", "category": "价格与进出口", "metric": "CPI同比"},
    ),
    _indicator(
        code="CN_EXPORT_PRICE_INDEX",
        name="China export price index",
        domain="country_macro",
        region="China",
        unit="index",
        frequency="monthly",
        provider="unavailable",
        source="Pending:Customs/Wind",
        description="出口价格指数用于拆分出口量价。",
        display_order=218,
        selectors={"country": "China", "category": "价格与进出口", "metric": "出口价格"},
        availability=_availability_for("CN_EXPORT_PRICE_INDEX"),
    ),
    _indicator(
        code="CN_IMPORT_PRICE_INDEX",
        name="China import price index",
        domain="country_macro",
        region="China",
        unit="index",
        frequency="monthly",
        provider="unavailable",
        source="Pending:Customs/Wind",
        description="进口价格指数用于观察输入性价格变化。",
        display_order=219,
        selectors={"country": "China", "category": "价格与进出口", "metric": "进口价格"},
        availability=_availability_for("CN_IMPORT_PRICE_INDEX"),
    ),
    _indicator(
        code="CN_SHCOMP",
        name="SSE Composite Index",
        domain="country_macro",
        region="China",
        unit="index",
        frequency="daily",
        provider="akshare_china",
        source=AKSHARE_CHINA_SERIES["CN_SHCOMP"]["source"],
        description="上证综指用于补充观察国内金融市场风险偏好。",
        display_order=233,
        selectors={"country": "China", "category": "汇率与金融", "metric": "上证综指"},
    ),
]


def get_catalog() -> list[IndicatorDefinition]:
    """返回按展示顺序排序的指标目录。"""

    return sorted(
        [
            *_treasury_indicators(),
            *_FRED_INDICATORS,
            *_COAL_PUBLIC_INDICATORS,
            *_COAL_AKSHARE_INDICATORS,
            *_COAL_UNAVAILABLE_INDICATORS,
            *_UNAVAILABLE_INDICATORS,
            *_CHINA_DOMESTIC_UNAVAILABLE_INDICATORS,
            *_CHINA_DATA_INDICATORS,
            *_CHINA_AKSHARE_EXTRA_INDICATORS,
            *_CHINA_WORLD_BANK_EXTRA_INDICATORS,
            *_KEY_GATED_INDICATORS,
            *_CRUDE_OIL_AKSHARE_INDICATORS,
            *_OIL_SHIPPING_INDICATORS,
            *_ROUTE_TANKER_PENDING_INDICATORS,
            *_EIA_PUBLIC_INDICATORS,
            *_EXCHANGE_PENDING_INDICATORS,
            *_NONFERROUS_AKSHARE_INDICATORS,
            *_POWER_AKSHARE_INDICATORS,
            *_POWER_AKSHARE_EXTRA_INDICATORS,
            *_POWER_UNAVAILABLE_INDICATORS,
            *_ADDITIONAL_MACRO_AKSHARE_INDICATORS,
            *_WORLD_BANK_INDICATORS,
        ],
        key=lambda item: item.display_order,
    )


def get_indicator(code: str) -> IndicatorDefinition:
    """按指标代码返回指标定义。"""

    for indicator in get_catalog():
        if indicator.code == code:
            return indicator
    raise KeyError(f"Unknown indicator code: {code}")
